# Small Business Sales Analytics & Interactive Dashboard

## Project Overview

This project demonstrates an end-to-end data analytics workflow using a realistic small-business sales dataset.

The objective is to transform raw and potentially inconsistent transaction data into a clean, validated dataset and use it to generate meaningful business insights.

The project follows the workflow:

**Data Collection → Data Profiling → Data Cleaning → Data Validation → Exploratory Data Analysis → Interactive Visualization → Business Insights**

### Business Questions

This analysis aims to answer the following questions:

1. How are sales and profit changing over time?
2. Which products and categories generate the most revenue?
3. Which provinces and cities perform best?
4. Which sales channels contribute the most sales?
5. What is the average order value?
6. How do discounts affect profitability?
7. What actionable insights can management obtain from the data?

### Tools & Technologies

* Python
* pandas
* NumPy
* Plotly
* Google Colab
* Power BI
* Excel/CSV

### Skills Demonstrated

* Data profiling
* Data cleaning
* Missing-value handling
* Duplicate detection
* Data validation
* Exploratory data analysis
* KPI development
* Interactive data visualization
* Business insight generation
* Dashboard preparation

> **Note:** This is a fictional portfolio project created to demonstrate data analytics and business intelligence skills. No real customer information is used.

In [1]:
import pandas as pd
import numpy as np

print("Python is working!")

Python is working!

## 1. Creating a Realistic Raw Sales Dataset

For this portfolio project, I am creating a synthetic transactional dataset representing sales from a fictional Canadian small business.

Creating the dataset allows me to demonstrate the complete analytics workflow, including data-quality assessment and cleaning, without exposing any real customer information.

The dataset will contain transaction-level information such as:

* Order information
* Customer information
* Geographic information
* Product and category information
* Quantity and pricing
* Discounts
* Sales and cost
* Profit
* Payment method
* Sales channel

### Why create a "messy" dataset?

Real-world business data is rarely perfectly structured. Before analysis, an analyst must identify and resolve data-quality issues.

Therefore, this raw dataset intentionally contains examples of:

* Duplicate transactions
* Missing values
* Inconsistent text formatting
* Extra whitespace
* Invalid dates
* Invalid numerical values

The purpose is to demonstrate the process of **profiling, cleaning and validating data before using it for business analysis.**

In [2]:
# ============================================
# STEP 2: CREATE RAW SALES DATASET
# ============================================

import pandas as pd
import numpy as np

# Make the results reproducible
np.random.seed(42)

# Number of original transactions
n = 10000

# --------------------------------------------
# Business locations
# --------------------------------------------

locations = {
    "Alberta": ["Edmonton", "Calgary", "Red Deer", "Lethbridge"],
    "British Columbia": ["Vancouver", "Surrey", "Victoria", "Kelowna"],
    "Ontario": ["Toronto", "Ottawa", "Mississauga", "Hamilton"],
    "Manitoba": ["Winnipeg", "Brandon"],
    "Saskatchewan": ["Saskatoon", "Regina"]
}

# --------------------------------------------
# Products
# --------------------------------------------

products = [
    ("Laptop Pro 14", "Electronics", 1299),
    ("Wireless Headphones", "Electronics", 179),
    ("Office Monitor 27", "Electronics", 349),
    ("Mechanical Keyboard", "Accessories", 129),
    ("Wireless Mouse", "Accessories", 49),
    ("USB-C Dock", "Accessories", 159),
    ("Office Chair", "Furniture", 429),
    ("Standing Desk", "Furniture", 699),
    ("Desk Lamp", "Furniture", 89),
    ("Notebook Pack", "Office Supplies", 24),
    ("Printer Paper", "Office Supplies", 39),
    ("Ink Cartridge", "Office Supplies", 79),
    ("Webcam HD", "Electronics", 99),
    ("Tablet 11", "Electronics", 499),
    ("Backpack", "Accessories", 79)
]

# --------------------------------------------
# Dates
# --------------------------------------------

dates = pd.date_range(
    start="2025-01-01",
    end="2026-06-30",
    freq="D"
)

date_choices = np.random.choice(dates, n)

# --------------------------------------------
# Province and city
# --------------------------------------------

province_choices = np.random.choice(
    list(locations.keys()),
    n,
    p=[0.30, 0.18, 0.32, 0.10, 0.10]
)

city_choices = [
    np.random.choice(locations[province])
    for province in province_choices
]

# --------------------------------------------
# Product information
# --------------------------------------------

product_indices = np.random.randint(
    0,
    len(products),
    n
)

product_names = [
    products[i][0]
    for i in product_indices
]

categories = [
    products[i][1]
    for i in product_indices
]

unit_prices = np.array([
    products[i][2]
    for i in product_indices
], dtype=float)

# --------------------------------------------
# Quantity and discount
# --------------------------------------------

quantity = np.random.choice(
    [1, 2, 3, 4, 5, 6],
    n,
    p=[0.30, 0.27, 0.18, 0.12, 0.08, 0.05]
)

discount = np.random.choice(
    [0, 0.05, 0.10, 0.15, 0.20],
    n,
    p=[0.45, 0.20, 0.20, 0.10, 0.05]
)

# --------------------------------------------
# Financial calculations
# --------------------------------------------

sales = (
    quantity
    * unit_prices
    * (1 - discount)
)

cost_ratio = np.random.uniform(
    0.55,
    0.82,
    n
)

cost = sales * cost_ratio

profit = sales - cost

# --------------------------------------------
# Customers
# --------------------------------------------

customer_numbers = np.random.randint(
    1001,
    4200,
    n
)

customer_ids = [
    f"CUST-{x}"
    for x in customer_numbers
]

customer_names = [
    f"Customer {x}"
    for x in customer_numbers
]

# --------------------------------------------
# Payment and sales channel
# --------------------------------------------

payment_methods = [
    "Credit Card",
    "Debit",
    "E-Transfer",
    "PayPal"
]

sales_channels = [
    "Online",
    "Retail Store",
    "Wholesale"
]

# --------------------------------------------
# Build DataFrame
# --------------------------------------------

raw_sales = pd.DataFrame({

    "Order_ID": [
        f"ORD-{100000 + i}"
        for i in range(n)
    ],

    "Order_Date": pd.to_datetime(
        date_choices
    ).strftime("%Y-%m-%d"),

    "Customer_ID": customer_ids,

    "Customer_Name": customer_names,

    "Province": province_choices,

    "City": city_choices,

    "Product": product_names,

    "Category": categories,

    "Quantity": quantity,

    "Unit_Price": np.round(
        unit_prices,
        2
    ),

    "Discount": discount,

    "Sales": np.round(
        sales,
        2
    ),

    "Cost": np.round(
        cost,
        2
    ),

    "Profit": np.round(
        profit,
        2
    ),

    "Payment_Method": np.random.choice(
        payment_methods,
        n
    ),

    "Sales_Channel": np.random.choice(
        sales_channels,
        n,
        p=[0.55, 0.30, 0.15]
    )
})

# ============================================
# INTRODUCE REALISTIC DATA-QUALITY PROBLEMS
# ============================================

# 1. Add duplicate transactions
duplicates = raw_sales.sample(
    75,
    random_state=7
)

raw_sales = pd.concat(
    [raw_sales, duplicates],
    ignore_index=True
)

# 2. Missing values
for column, count in [
    ("City", 55),
    ("Customer_Name", 40),
    ("Discount", 30),
    ("Payment_Method", 25)
]:

    indexes = np.random.choice(
        raw_sales.index,
        count,
        replace=False
    )

    raw_sales.loc[
        indexes,
        column
    ] = np.nan

# 3. Inconsistent capitalization
indexes = np.random.choice(
    raw_sales.index,
    120,
    replace=False
)

raw_sales.loc[
    indexes[:40],
    "Province"
] = raw_sales.loc[
    indexes[:40],
    "Province"
].str.lower()

raw_sales.loc[
    indexes[40:80],
    "Category"
] = raw_sales.loc[
    indexes[40:80],
    "Category"
].str.upper()

raw_sales.loc[
    indexes[80:],
    "Sales_Channel"
] = raw_sales.loc[
    indexes[80:],
    "Sales_Channel"
].str.lower()

# 4. Extra whitespace
indexes = np.random.choice(
    raw_sales.index,
    100,
    replace=False
)

raw_sales.loc[
    indexes,
    "Product"
] = raw_sales.loc[
    indexes,
    "Product"
].astype(str).apply(
    lambda x: "  " + x + " "
)

# 5. Invalid dates
bad_date_indexes = np.random.choice(
    raw_sales.index,
    12,
    replace=False
)

raw_sales.loc[
    bad_date_indexes[:6],
    "Order_Date"
] = "2026-13-40"

raw_sales.loc[
    bad_date_indexes[6:],
    "Order_Date"
] = "not_a_date"

# 6. Invalid numerical values
anomaly_indexes = np.random.choice(
    raw_sales.index,
    10,
    replace=False
)

raw_sales.loc[
    anomaly_indexes[:5],
    "Quantity"
] = 0

raw_sales.loc[
    anomaly_indexes[5:],
    "Unit_Price"
] = -50

# Shuffle the dataset
raw_sales = raw_sales.sample(
    frac=1,
    random_state=42
).reset_index(drop=True)

# ============================================
# DISPLAY RESULTS
# ============================================

print("RAW DATASET CREATED")
print("=" * 50)

print(f"Rows: {raw_sales.shape[0]:,}")
print(f"Columns: {raw_sales.shape[1]}")

print("\nFirst 5 records:")
display(raw_sales.head())

print("\nColumn names:")
print(raw_sales.columns.tolist())

RAW DATASET CREATED
==================================================
Rows: 10,075
Columns: 16

First 5 records:

,Order_ID,Order_Date,Customer_ID,Customer_Name,Province,City,Product,Category,Quantity,Unit_Price,Discount,Sales,Cost,Profit,Payment_Method,Sales_Channel
0,ORD-104180,2025-05-26,CUST-1050,Customer 1050,Ontario,Toronto,Ink Cartridge,Office Supplies,5,79.0,0.00,395.00,320.66,74.34,Credit Card,Online
1,ORD-100318,2025-05-07,CUST-3348,Customer 3348,British Columbia,Kelowna,Laptop Pro 14,Electronics,5,1299.0,0.00,6495.00,3808.76,2686.24,E-Transfer,Retail Store
2,ORD-103692,2026-01-18,CUST-2679,Customer 2679,British Columbia,Victoria,Laptop Pro 14,Electronics,1,1299.0,0.00,1299.00,989.36,309.64,PayPal,Online
3,ORD-101156,2026-06-05,CUST-2504,Customer 2504,British Columbia,Kelowna,Standing Desk,Furniture,2,699.0,0.00,1398.00,803.52,594.48,Debit,Online
4,ORD-100033,2026-05-20,CUST-1976,Customer 1976,Ontario,Mississauga,Office Chair,Furniture,1,429.0,0.05,407.55,279.30,128.25,Credit Card,Online

Column names:
['Order_ID', 'Order_Date', 'Customer_ID', 'Customer_Name', 'Province', 'City', 'Product', 'Category', 'Quantity', 'Unit_Price', 'Discount', 'Sales', 'Cost', 'Profit', 'Payment_Method', 'Sales_Channel']

## 2. Data Profiling & Quality Assessment

Before cleaning the dataset, I will first profile the raw data to understand its structure and identify potential data-quality issues.

This step is important because cleaning decisions should be based on evidence from the data rather than assumptions.

### Areas being assessed

* Dataset dimensions
* Column names and data types
* Missing values
* Duplicate records
* Unique values in categorical fields
* Numerical distributions
* Potentially invalid values

The results of this assessment will determine the cleaning rules used in the next stage.

In [3]:
# ============================================
# DATASET OVERVIEW
# ============================================

print("DATASET OVERVIEW")
print("=" * 50)

print(f"Number of rows: {raw_sales.shape[0]:,}")
print(f"Number of columns: {raw_sales.shape[1]}")

print("\nColumn names:")
for column in raw_sales.columns:
    print("-", column)

print("\nFirst 5 records:")
display(raw_sales.head())

DATASET OVERVIEW
==================================================
Number of rows: 10,075
Number of columns: 16

Column names:
- Order_ID
- Order_Date
- Customer_ID
- Customer_Name
- Province
- City
- Product
- Category
- Quantity
- Unit_Price
- Discount
- Sales
- Cost
- Profit
- Payment_Method
- Sales_Channel

First 5 records:

,Order_ID,Order_Date,Customer_ID,Customer_Name,Province,City,Product,Category,Quantity,Unit_Price,Discount,Sales,Cost,Profit,Payment_Method,Sales_Channel
0,ORD-104180,2025-05-26,CUST-1050,Customer 1050,Ontario,Toronto,Ink Cartridge,Office Supplies,5,79.0,0.00,395.00,320.66,74.34,Credit Card,Online
1,ORD-100318,2025-05-07,CUST-3348,Customer 3348,British Columbia,Kelowna,Laptop Pro 14,Electronics,5,1299.0,0.00,6495.00,3808.76,2686.24,E-Transfer,Retail Store
2,ORD-103692,2026-01-18,CUST-2679,Customer 2679,British Columbia,Victoria,Laptop Pro 14,Electronics,1,1299.0,0.00,1299.00,989.36,309.64,PayPal,Online
3,ORD-101156,2026-06-05,CUST-2504,Customer 2504,British Columbia,Kelowna,Standing Desk,Furniture,2,699.0,0.00,1398.00,803.52,594.48,Debit,Online
4,ORD-100033,2026-05-20,CUST-1976,Customer 1976,Ontario,Mississauga,Office Chair,Furniture,1,429.0,0.05,407.55,279.30,128.25,Credit Card,Online

### Data Types Assessment

Understanding the data type of each field is important before analysis.

For example:

* Dates should be stored as datetime values.
* Quantities and prices should be numeric.
* Categorical information should be treated as text/categories.

Incorrect data types can lead to inaccurate calculations and visualizations, so they will be reviewed before the cleaning stage.

In [4]:
# ============================================
# DATA TYPES
# ============================================

print("DATA TYPES")
print("=" * 50)

data_types = pd.DataFrame({
    "Column": raw_sales.columns,
    "Data_Type": raw_sales.dtypes.astype(str).values,
    "Missing_Values": raw_sales.isna().sum().values,
    "Unique_Values": raw_sales.nunique().values
})

display(data_types)

DATA TYPES
==================================================

            Column Data_Type  Missing_Values  Unique_Values
0         Order_ID    object               0          10000
1       Order_Date    object               0            548
2      Customer_ID    object               0           3039
3    Customer_Name    object              40           3035
4         Province    object               0             10
5             City    object              55             16
6          Product    object               0             30
7         Category    object               0              8
8         Quantity     int64               0              7
9       Unit_Price   float64               0             15
10        Discount   float64              30              5
11           Sales   float64               0            404
12            Cost   float64               0           9149
13          Profit   float64               0           8385
14  Payment_Method    object              25              4
15   Sales_Channel    object               0              6

### Missing Value Assessment

Missing values can affect calculations, visualizations and business conclusions.

Rather than automatically deleting missing records, I will first identify:

1. Which columns contain missing values.
2. How many values are missing.
3. The percentage of the column affected.

The appropriate treatment will depend on the business meaning of each field.

In [5]:
# ============================================
# MISSING VALUE ANALYSIS
# ============================================

missing_analysis = pd.DataFrame({
    "Missing_Count": raw_sales.isna().sum(),
    "Missing_Percentage": (
        raw_sales.isna().mean() * 100
    ).round(2)
})

missing_analysis = (
    missing_analysis
    .sort_values("Missing_Count", ascending=False)
)

display(missing_analysis)

                Missing_Count  Missing_Percentage
City                       55                0.55
Customer_Name              40                0.40
Discount                   30                0.30
Payment_Method             25                0.25
Customer_ID                 0                0.00
Province                    0                0.00
Order_Date                  0                0.00
Order_ID                    0                0.00
Category                    0                0.00
Product                     0                0.00
Unit_Price                  0                0.00
Quantity                    0                0.00
Sales                       0                0.00
Cost                        0                0.00
Profit                      0                0.00
Sales_Channel               0                0.00

### Duplicate Record Assessment

Duplicate transactions can inflate sales, order counts and other business metrics.

I will therefore check both:

* Completely duplicated rows
* Duplicate Order IDs

The second check is particularly important because `Order_ID` is intended to identify an individual transaction.

In [6]:
# ============================================
# DUPLICATE ANALYSIS
# ============================================

full_duplicates = raw_sales.duplicated().sum()

duplicate_order_ids = (
    raw_sales["Order_ID"]
    .duplicated()
    .sum()
)

print("DUPLICATE ANALYSIS")
print("=" * 50)

print(f"Completely duplicated rows: {full_duplicates:,}")
print(f"Duplicate Order IDs: {duplicate_order_ids:,}")

print("\nExample duplicate transactions:")

duplicate_examples = raw_sales[
    raw_sales["Order_ID"].duplicated(keep=False)
].sort_values("Order_ID")

display(duplicate_examples.head(10))

DUPLICATE ANALYSIS
==================================================
Completely duplicated rows: 72
Duplicate Order IDs: 75

Example duplicate transactions:

,Order_ID,Order_Date,Customer_ID,Customer_Name,Province,City,Product,Category,Quantity,Unit_Price,Discount,Sales,Cost,Profit,Payment_Method,Sales_Channel
3287,ORD-100052,2025-03-22,CUST-2394,Customer 2394,British Columbia,Surrey,Notebook Pack,Office Supplies,2,24.0,0.05,45.60,32.99,12.61,PayPal,Online
6584,ORD-100052,2025-03-22,CUST-2394,Customer 2394,British Columbia,Surrey,Notebook Pack,Office Supplies,2,24.0,0.05,45.60,32.99,12.61,PayPal,Online
2552,ORD-100065,2025-09-09,CUST-1549,Customer 1549,Alberta,Calgary,Laptop Pro 14,Electronics,2,1299.0,0.00,2598.00,1669.57,928.43,PayPal,Retail Store
9375,ORD-100065,2025-09-09,CUST-1549,Customer 1549,Alberta,Calgary,Laptop Pro 14,Electronics,2,1299.0,0.00,2598.00,1669.57,928.43,PayPal,Retail Store
4701,ORD-100270,2025-11-19,CUST-1511,Customer 1511,British Columbia,Vancouver,Office Monitor 27,Electronics,3,349.0,0.10,942.30,764.20,178.10,E-Transfer,Online
6122,ORD-100270,2025-11-19,CUST-1511,Customer 1511,British Columbia,Vancouver,Office Monitor 27,Electronics,3,349.0,0.10,942.30,764.20,178.10,E-Transfer,Online
2635,ORD-100403,2025-06-26,CUST-2731,Customer 2731,Saskatchewan,Saskatoon,Wireless Mouse,Accessories,3,49.0,0.05,139.65,84.10,55.55,PayPal,Online
1054,ORD-100403,2025-06-26,CUST-2731,Customer 2731,Saskatchewan,Saskatoon,Wireless Mouse,Accessories,3,49.0,0.05,139.65,84.10,55.55,PayPal,Online
6378,ORD-100438,2025-06-23,CUST-2322,Customer 2322,Alberta,Calgary,Wireless Headphones,Electronics,3,179.0,0.05,510.15,375.26,134.89,E-Transfer,Online
2268,ORD-100438,2025-06-23,CUST-2322,Customer 2322,Alberta,Calgary,Wireless Headphones,Electronics,3,179.0,0.05,510.15,375.26,134.89,E-Transfer,Online

### Numerical Data Validation

Numerical fields require validation before financial analysis.

For this dataset, the following rules will be investigated:

* Quantity should be greater than zero.
* Unit price should be greater than zero.
* Discount should be between 0% and 100%.
* Sales and cost should not contain unexpected negative values.

These checks help prevent invalid transactions from affecting business metrics.

In [7]:
# ============================================
# NUMERICAL VALIDATION
# ============================================

print("NUMERICAL VALIDATION")
print("=" * 50)

print("Quantity <= 0:")
display(
    raw_sales[raw_sales["Quantity"] <= 0]
)

print("\nUnit Price <= 0:")
display(
    raw_sales[raw_sales["Unit_Price"] <= 0]
)

print("\nDiscount outside expected range:")

display(
    raw_sales[
        (raw_sales["Discount"] < 0) |
        (raw_sales["Discount"] > 1)
    ]
)

NUMERICAL VALIDATION
==================================================
Quantity <= 0:

,Order_ID,Order_Date,Customer_ID,Customer_Name,Province,City,Product,Category,Quantity,Unit_Price,Discount,Sales,Cost,Profit,Payment_Method,Sales_Channel
1478,ORD-109061,2025-09-23,CUST-2791,Customer 2791,Saskatchewan,Regina,USB-C Dock,Accessories,0,159.0,0.00,954.0,600.42,353.58,Debit,Online
2453,ORD-101017,2026-05-06,CUST-1250,Customer 1250,Ontario,Toronto,Printer Paper,Office Supplies,0,39.0,0.00,78.0,47.76,30.24,Credit Card,Retail Store
3719,ORD-100938,2025-05-31,CUST-2259,Customer 2259,British Columbia,Kelowna,Desk Lamp,Furniture,0,89.0,0.00,178.0,142.84,35.16,E-Transfer,Online
6767,ORD-101845,2026-04-10,CUST-1294,Customer 1294,British Columbia,Victoria,Wireless Headphones,Electronics,0,179.0,0.05,680.2,500.96,179.24,Debit,Retail Store
9199,ORD-100235,2025-10-10,CUST-3866,Customer 3866,Ontario,Toronto,Webcam HD,Electronics,0,99.0,0.00,396.0,270.55,125.45,PayPal,Online

Unit Price <= 0:

,Order_ID,Order_Date,Customer_ID,Customer_Name,Province,City,Product,Category,Quantity,Unit_Price,Discount,Sales,Cost,Profit,Payment_Method,Sales_Channel
3421,ORD-102234,2026-01-12,CUST-2678,Customer 2678,Alberta,Edmonton,Wireless Mouse,Accessories,4,-50.0,0.00,196.00,132.51,63.49,E-Transfer,Online
3757,ORD-108055,2025-09-15,CUST-2787,Customer 2787,Manitoba,Brandon,Ink Cartridge,Office Supplies,5,-50.0,0.10,355.50,225.85,129.65,Debit,Online
8124,ORD-100819,2025-05-14,CUST-2295,Customer 2295,Manitoba,Winnipeg,Backpack,Accessories,3,-50.0,0.00,237.00,169.08,67.92,Credit Card,Online
8975,ORD-107083,2026-06-18,CUST-1367,Customer 1367,Ontario,Mississauga,Tablet 11,Electronics,5,-50.0,0.05,2370.25,1401.60,968.65,Credit Card,Retail Store
9671,ORD-100512,2025-05-02,CUST-2392,Customer 2392,British Columbia,Victoria,Printer Paper,Office Supplies,3,-50.0,0.00,117.00,88.61,28.39,PayPal,Online

Discount outside expected range:

Empty DataFrame
Columns: [Order_ID, Order_Date, Customer_ID, Customer_Name, Province, City, Product, Category, Quantity, Unit_Price, Discount, Sales, Cost, Profit, Payment_Method, Sales_Channel]
Index: []

### Categorical Consistency Assessment

Categorical fields can contain inconsistent representations of the same value.

For example:

* `Electronics`
* `ELECTRONICS`
* `electronics`

represent the same business category but would be treated as different groups during analysis.

I will therefore inspect unique values before standardizing the fields.

In [8]:
# ============================================
# CATEGORICAL VALUE CHECK
# ============================================

categorical_columns = [
    "Province",
    "Category",
    "Payment_Method",
    "Sales_Channel"
]

for column in categorical_columns:

    print("\n" + "=" * 50)
    print(f"{column.upper()}")

    print(
        raw_sales[column]
        .value_counts(dropna=False)
    )

==================================================
PROVINCE
Province
Ontario             3221
Alberta             2962
British Columbia    1817
Saskatchewan        1020
Manitoba            1015
ontario               14
alberta               12
saskatchewan           7
british columbia       6
manitoba               1
Name: count, dtype: int64

==================================================
CATEGORY
Category
Electronics        3252
Accessories        2689
Furniture          2048
Office Supplies    2046
ELECTRONICS          14
ACCESSORIES          10
OFFICE SUPPLIES      10
FURNITURE             6
Name: count, dtype: int64

==================================================
PAYMENT_METHOD
Payment_Method
Credit Card    2563
E-Transfer     2549
Debit          2477
PayPal         2461
NaN              25
Name: count, dtype: int64

==================================================
SALES_CHANNEL
Sales_Channel
Online          5517
Retail Store    3047
Wholesale       1471
online            22
retail store      13
wholesale          5
Name: count, dtype: int64

## Data Profiling Summary

The initial profiling identified several data-quality issues that should be addressed before performing business analysis.

### Identified Issues

* Duplicate transaction records
* Duplicate Order IDs
* Missing values in selected fields
* Invalid date values
* Inconsistent capitalization
* Leading/trailing whitespace
* Non-positive quantities
* Invalid unit prices
* Potentially inconsistent categorical values

### Next Step

Based on these findings, I will define and apply data-cleaning rules while preserving as much valid information as possible.

After cleaning, the resulting dataset will be validated again to confirm that the identified issues have been addressed.

## 2. Data Cleaning

After profiling the raw dataset, the next step is to clean the data before performing any business analysis.

The goal is not simply to remove rows. Each cleaning decision should have a clear reason and should preserve valid business information wherever possible.

### Cleaning Strategy

The following rules will be applied:

1. Remove duplicate transactions using `Order_ID`.
2. Convert the order date to a proper datetime format.
3. Remove transactions with invalid dates because they cannot be reliably analyzed over time.
4. Remove records with zero or negative quantities.
5. Remove records with zero or negative unit prices.
6. Standardize text fields by removing unnecessary whitespace and correcting inconsistent capitalization.
7. Replace missing customer and categorical information with `"Unknown"` where appropriate.
8. Treat a missing discount as no discount (`0%`) because the transaction does not indicate that a discount was applied.
9. Recalculate sales and profit from the cleaned transaction values to ensure financial calculations are internally consistent.
10. Create additional analytical fields that will be useful for later analysis.

Importantly, the original `raw_sales` dataset will not be modified. A separate `clean_sales` dataset will be created so that the cleaning process remains reproducible and auditable.

In [9]:
# ============================================
# STEP 4: DATA CLEANING
# ============================================

# Keep the original raw dataset unchanged
clean_sales = raw_sales.copy()

print("Starting data cleaning...")
print(f"Initial rows: {len(clean_sales):,}")

# --------------------------------------------
# 1. Remove duplicate transactions
# --------------------------------------------

before_duplicates = len(clean_sales)

clean_sales = clean_sales.drop_duplicates(
    subset="Order_ID",
    keep="first"
)

duplicates_removed = before_duplicates - len(clean_sales)

print(f"Duplicate transactions removed: {duplicates_removed:,}")


# --------------------------------------------
# 2. Standardize text fields
# --------------------------------------------

text_columns = [
    "Customer_Name",
    "Province",
    "City",
    "Category",
    "Payment_Method",
    "Sales_Channel"
]

for column in text_columns:
    clean_sales[column] = (
        clean_sales[column]
        .astype("string")
        .str.strip()
        .str.title()
    )

# Product names only need whitespace cleanup
clean_sales["Product"] = (
    clean_sales["Product"]
    .astype("string")
    .str.strip()
)


# --------------------------------------------
# 3. Convert dates
# --------------------------------------------

clean_sales["Order_Date"] = pd.to_datetime(
    clean_sales["Order_Date"],
    errors="coerce"
)

invalid_dates = clean_sales["Order_Date"].isna().sum()

print(f"Invalid dates identified: {invalid_dates:,}")


# --------------------------------------------
# 4. Convert numerical columns
# --------------------------------------------

numeric_columns = [
    "Quantity",
    "Unit_Price",
    "Discount",
    "Sales",
    "Cost",
    "Profit"
]

for column in numeric_columns:
    clean_sales[column] = pd.to_numeric(
        clean_sales[column],
        errors="coerce"
    )


# --------------------------------------------
# 5. Remove invalid dates
# --------------------------------------------

before_dates = len(clean_sales)

clean_sales = clean_sales[
    clean_sales["Order_Date"].notna()
]

print(
    f"Rows removed because of invalid dates: "
    f"{before_dates - len(clean_sales):,}"
)


# --------------------------------------------
# 6. Remove invalid quantities
# --------------------------------------------

before_quantity = len(clean_sales)

clean_sales = clean_sales[
    clean_sales["Quantity"] > 0
]

print(
    f"Rows removed because of invalid quantity: "
    f"{before_quantity - len(clean_sales):,}"
)


# --------------------------------------------
# 7. Remove invalid unit prices
# --------------------------------------------

before_price = len(clean_sales)

clean_sales = clean_sales[
    clean_sales["Unit_Price"] > 0
]

print(
    f"Rows removed because of invalid unit price: "
    f"{before_price - len(clean_sales):,}"
)


# --------------------------------------------
# 8. Handle missing values
# --------------------------------------------

clean_sales["Customer_Name"] = (
    clean_sales["Customer_Name"]
    .fillna("Unknown")
)

clean_sales["Province"] = (
    clean_sales["Province"]
    .fillna("Unknown")
)

clean_sales["City"] = (
    clean_sales["City"]
    .fillna("Unknown")
)

clean_sales["Payment_Method"] = (
    clean_sales["Payment_Method"]
    .fillna("Unknown")
)

clean_sales["Discount"] = (
    clean_sales["Discount"]
    .fillna(0)
)


# --------------------------------------------
# 9. Validate discount values
# --------------------------------------------

clean_sales = clean_sales[
    (clean_sales["Discount"] >= 0) &
    (clean_sales["Discount"] <= 1)
]


# --------------------------------------------
# 10. Recalculate financial metrics
# --------------------------------------------

clean_sales["Sales"] = (
    clean_sales["Quantity"]
    * clean_sales["Unit_Price"]
    * (1 - clean_sales["Discount"])
)

clean_sales["Sales"] = clean_sales["Sales"].round(2)

clean_sales["Profit"] = (
    clean_sales["Sales"]
    - clean_sales["Cost"]
)

clean_sales["Profit"] = clean_sales["Profit"].round(2)


# --------------------------------------------
# 11. Create analytical fields
# --------------------------------------------

clean_sales["Profit_Margin"] = np.where(
    clean_sales["Sales"] != 0,
    clean_sales["Profit"] / clean_sales["Sales"],
    0
)

clean_sales["Profit_Margin"] = (
    clean_sales["Profit_Margin"].round(4)
)

clean_sales["Year"] = (
    clean_sales["Order_Date"].dt.year
)

clean_sales["Month"] = (
    clean_sales["Order_Date"].dt.to_period("M")
    .astype(str)
)

clean_sales["Month_Name"] = (
    clean_sales["Order_Date"]
    .dt.strftime("%B")
)


# --------------------------------------------
# 12. Sort the cleaned dataset
# --------------------------------------------

clean_sales = clean_sales.sort_values(
    "Order_Date"
).reset_index(drop=True)


# --------------------------------------------
# FINAL RESULT
# --------------------------------------------

print("\n" + "=" * 50)
print("DATA CLEANING COMPLETE")
print("=" * 50)

print(f"Final rows: {len(clean_sales):,}")
print(f"Final columns: {len(clean_sales.columns)}")

print("\nCleaned dataset preview:")
display(clean_sales.head())

print("\nRemaining missing values:")
display(
    clean_sales.isna().sum()
    .sort_values(ascending=False)
    .head(10)
)

Starting data cleaning...
Initial rows: 10,075
Duplicate transactions removed: 75
Invalid dates identified: 12
Rows removed because of invalid dates: 12
Rows removed because of invalid quantity: 5
Rows removed because of invalid unit price: 5

==================================================
DATA CLEANING COMPLETE
==================================================
Final rows: 9,978
Final columns: 20

Cleaned dataset preview:

,Order_ID,Order_Date,Customer_ID,Customer_Name,Province,City,Product,Category,Quantity,Unit_Price,Discount,Sales,Cost,Profit,Payment_Method,Sales_Channel,Profit_Margin,Year,Month,Month_Name
0,ORD-108345,2025-01-01,CUST-1422,Customer 1422,Ontario,Mississauga,Webcam HD,Electronics,4,99.0,0.20,316.8,216.30,100.50,Paypal,Online,0.3172,2025,2025-01,January
1,ORD-104876,2025-01-01,CUST-3656,Customer 3656,Saskatchewan,Regina,Webcam HD,Electronics,4,99.0,0.05,376.2,248.67,127.53,Paypal,Retail Store,0.3390,2025,2025-01,January
2,ORD-101535,2025-01-01,CUST-1778,Customer 1778,Saskatchewan,Saskatoon,Standing Desk,Furniture,3,699.0,0.00,2097.0,1314.25,782.75,E-Transfer,Online,0.3733,2025,2025-01,January
3,ORD-102266,2025-01-01,CUST-3811,Customer 3811,Alberta,Calgary,Printer Paper,Office Supplies,2,39.0,0.05,74.1,43.63,30.47,Unknown,Retail Store,0.4112,2025,2025-01,January
4,ORD-100845,2025-01-01,CUST-2760,Customer 2760,Alberta,Red Deer,USB-C Dock,Accessories,1,159.0,0.00,159.0,101.35,57.65,Paypal,Online,0.3626,2025,2025-01,January

Remaining missing values:

Order_ID         0
Order_Date       0
Customer_ID      0
Customer_Name    0
Province         0
City             0
Product          0
Category         0
Quantity         0
Unit_Price       0
dtype: int64

## Data Cleaning Results

The raw dataset has now been transformed into a cleaner and analysis-ready dataset.

The cleaning process addressed duplicate transactions, invalid dates, invalid numerical values, inconsistent text formatting and missing values.

The original raw dataset was preserved, while the cleaned version was stored separately as `clean_sales`.

### Additional Analytical Fields

Several fields were also created to support the next stage of analysis:

* **Profit Margin** — measures profit relative to sales.
* **Year** — allows yearly comparisons.
* **Month** — supports monthly sales and profit trends.
* **Month Name** — useful for visual summaries.

### Why This Matters

Cleaning the data before analysis reduces the risk of producing misleading business results.

The next step is **Data Validation**, where I will test whether the cleaned dataset now meets the expected quality rules before using it to generate business insights.

## 3. Data Validation

After cleaning the dataset, I will validate the results before proceeding with exploratory analysis.

Data validation is an important part of the analytics workflow because a dataset can appear clean while still containing logical or business-rule errors.

The validation checks will confirm that:

* Order IDs are unique.
* Required fields contain no missing values.
* Dates fall within the expected period.
* Quantities are positive.
* Unit prices are positive.
* Discounts fall between 0% and 100%.
* Sales calculations are consistent with quantity, price and discount.
* Profit calculations are consistent with sales and cost.
* Profit margins are within a reasonable range.

These checks provide confidence that the cleaned dataset is suitable for further analysis and dashboard development.

In [10]:
# ============================================
# STEP 5: DATA VALIDATION
# ============================================

print("DATA VALIDATION")
print("=" * 60)


# --------------------------------------------
# 1. Check duplicate Order IDs
# --------------------------------------------

duplicate_orders = clean_sales["Order_ID"].duplicated().sum()

print("\n1. Duplicate Order IDs")
print(f"Duplicate Order IDs found: {duplicate_orders}")


# --------------------------------------------
# 2. Check missing values
# --------------------------------------------

total_missing = clean_sales.isna().sum().sum()

print("\n2. Missing Values")
print(f"Total missing values: {total_missing}")


# --------------------------------------------
# 3. Check date range
# --------------------------------------------

min_date = clean_sales["Order_Date"].min()
max_date = clean_sales["Order_Date"].max()

print("\n3. Date Range")
print(f"Minimum date: {min_date.date()}")
print(f"Maximum date: {max_date.date()}")


# --------------------------------------------
# 4. Check quantities
# --------------------------------------------

invalid_quantity = (
    clean_sales["Quantity"] <= 0
).sum()

print("\n4. Quantity Validation")
print(f"Non-positive quantities: {invalid_quantity}")


# --------------------------------------------
# 5. Check unit prices
# --------------------------------------------

invalid_price = (
    clean_sales["Unit_Price"] <= 0
).sum()

print("\n5. Unit Price Validation")
print(f"Non-positive unit prices: {invalid_price}")


# --------------------------------------------
# 6. Check discounts
# --------------------------------------------

invalid_discount = (
    (clean_sales["Discount"] < 0) |
    (clean_sales["Discount"] > 1)
).sum()

print("\n6. Discount Validation")
print(f"Invalid discounts: {invalid_discount}")


# --------------------------------------------
# 7. Validate Sales calculation
# --------------------------------------------

expected_sales = (
    clean_sales["Quantity"]
    * clean_sales["Unit_Price"]
    * (1 - clean_sales["Discount"])
)

sales_difference = (
    clean_sales["Sales"] - expected_sales
).abs()

sales_errors = (
    sales_difference > 0.01
).sum()

print("\n7. Sales Calculation Validation")
print(f"Sales calculation errors: {sales_errors}")


# --------------------------------------------
# 8. Validate Profit calculation
# --------------------------------------------

expected_profit = (
    clean_sales["Sales"]
    - clean_sales["Cost"]
)

profit_difference = (
    clean_sales["Profit"] - expected_profit
).abs()

profit_errors = (
    profit_difference > 0.01
).sum()

print("\n8. Profit Calculation Validation")
print(f"Profit calculation errors: {profit_errors}")


# --------------------------------------------
# 9. Validate Profit Margin
# --------------------------------------------

invalid_margin = (
    (clean_sales["Profit_Margin"] < -1) |
    (clean_sales["Profit_Margin"] > 1)
).sum()

print("\n9. Profit Margin Validation")
print(f"Invalid profit margins: {invalid_margin}")


# --------------------------------------------
# 10. Create validation summary
# --------------------------------------------

validation_results = pd.DataFrame({
    "Validation_Check": [
        "Duplicate Order IDs",
        "Missing Values",
        "Non-positive Quantities",
        "Non-positive Unit Prices",
        "Invalid Discounts",
        "Sales Calculation Errors",
        "Profit Calculation Errors",
        "Invalid Profit Margins"
    ],

    "Issues_Found": [
        duplicate_orders,
        total_missing,
        invalid_quantity,
        invalid_price,
        invalid_discount,
        sales_errors,
        profit_errors,
        invalid_margin
    ]
})

validation_results["Status"] = np.where(
    validation_results["Issues_Found"] == 0,
    "PASS",
    "REVIEW"
)

print("\n" + "=" * 60)
print("VALIDATION SUMMARY")
print("=" * 60)

display(validation_results)

DATA VALIDATION
============================================================

1. Duplicate Order IDs
Duplicate Order IDs found: 0

2. Missing Values
Total missing values: 0

3. Date Range
Minimum date: 2025-01-01
Maximum date: 2026-06-30

4. Quantity Validation
Non-positive quantities: 0

5. Unit Price Validation
Non-positive unit prices: 0

6. Discount Validation
Invalid discounts: 0

7. Sales Calculation Validation
Sales calculation errors: 0

8. Profit Calculation Validation
Profit calculation errors: 0

9. Profit Margin Validation
Invalid profit margins: 0

============================================================
VALIDATION SUMMARY
============================================================

            Validation_Check  Issues_Found Status
0        Duplicate Order IDs             0   PASS
1             Missing Values             0   PASS
2    Non-positive Quantities             0   PASS
3   Non-positive Unit Prices             0   PASS
4          Invalid Discounts             0   PASS
5   Sales Calculation Errors             0   PASS
6  Profit Calculation Errors             0   PASS
7     Invalid Profit Margins             0   PASS

## Data Validation Summary

The cleaned dataset was subjected to a series of quality and consistency checks.

The validation process confirms whether the dataset satisfies the defined business rules before analysis begins.

A validation status of **PASS** indicates that no issues were identified for that particular check.

This step is important because reliable analysis depends on reliable data. By validating the cleaned dataset before creating visualizations and KPIs, I can reduce the risk of presenting incorrect business conclusions.

### Next Step

With the dataset cleaned and validated, I can now move into **Exploratory Data Analysis (EDA)**.

The EDA stage will focus on understanding sales performance, profitability, products, geography, customer activity and sales channels.

## 4. Exploratory Data Analysis

With the dataset cleaned and validated, the next stage is Exploratory Data Analysis (EDA).

The purpose of EDA is to understand what is happening in the business before building a dashboard or making recommendations.

I will begin by calculating key performance indicators (KPIs), followed by analysis of:

* Sales performance
* Profitability
* Product performance
* Category performance
* Geographic performance
* Sales channels
* Discounts
* Monthly trends

### Key Business KPIs

The initial KPIs will include:

* Total Sales
* Total Profit
* Total Orders
* Units Sold
* Average Order Value
* Overall Profit Margin

These metrics provide a high-level view of the business and will later become the foundation of the Power BI dashboard.

In [11]:
# ============================================
# STEP 6: EXPLORATORY DATA ANALYSIS
# PART 1 — KEY BUSINESS KPIs
# ============================================

total_sales = clean_sales["Sales"].sum()

total_profit = clean_sales["Profit"].sum()

total_orders = clean_sales["Order_ID"].nunique()

units_sold = clean_sales["Quantity"].sum()

average_order_value = (
    total_sales / total_orders
)

overall_profit_margin = (
    total_profit / total_sales
)


# --------------------------------------------
# Create KPI summary
# --------------------------------------------

kpi_summary = pd.DataFrame({
    "KPI": [
        "Total Sales",
        "Total Profit",
        "Total Orders",
        "Units Sold",
        "Average Order Value",
        "Overall Profit Margin"
    ],

    "Value": [
        total_sales,
        total_profit,
        total_orders,
        units_sold,
        average_order_value,
        overall_profit_margin
    ]
})


print("KEY BUSINESS KPIs")
print("=" * 50)

display(kpi_summary)

KEY BUSINESS KPIs
==================================================

                     KPI         Value
0            Total Sales  6.521863e+06
1           Total Profit  2.045769e+06
2           Total Orders  9.978000e+03
3             Units Sold  2.534900e+04
4    Average Order Value  6.536242e+02
5  Overall Profit Margin  3.136787e-01

In [12]:
# ============================================
# FORMAT KPI RESULTS FOR PRESENTATION
# ============================================

print("BUSINESS PERFORMANCE SNAPSHOT")
print("=" * 50)

print(f"Total Sales:          ${total_sales:,.2f}")
print(f"Total Profit:         ${total_profit:,.2f}")
print(f"Total Orders:         {total_orders:,}")
print(f"Units Sold:           {units_sold:,}")
print(f"Average Order Value:  ${average_order_value:,.2f}")
print(f"Profit Margin:        {overall_profit_margin:.2%}")

BUSINESS PERFORMANCE SNAPSHOT
==================================================
Total Sales:          $6,521,862.75
Total Profit:         $2,045,769.14
Total Orders:         9,978
Units Sold:           25,349
Average Order Value:  $653.62
Profit Margin:        31.37%

## Monthly Sales and Profit Trend

Understanding performance over time helps identify growth patterns, seasonal changes and periods of weaker performance.

For this analysis, transactions will be aggregated by month to examine:

* Monthly sales
* Monthly profit
* Monthly order volume

An interactive visualization will then be created using Plotly so that the trend can be explored directly.

In [13]:
# ============================================
# MONTHLY SALES AND PROFIT TREND
# ============================================

monthly_performance = (
    clean_sales
    .groupby("Month", as_index=False)
    .agg(
        Sales=("Sales", "sum"),
        Profit=("Profit", "sum"),
        Orders=("Order_ID", "nunique"),
        Units=("Quantity", "sum")
    )
)

monthly_performance.head()

     Month      Sales     Profit  Orders  Units
0  2025-01  376850.20  115501.88     579   1537
1  2025-02  303822.50   98154.98     474   1217
2  2025-03  402795.95  125605.22     576   1502
3  2025-04  377711.80  116960.48     573   1443
4  2025-05  326561.70  101964.64     565   1430

In [15]:
import plotly.express as px

# ============================================
# INTERACTIVE MONTHLY SALES TREND
# ============================================

fig = px.line(
    monthly_performance,
    x="Month",
    y="Sales",
    markers=True,
    title="Monthly Sales Trend",
    labels={
        "Month": "Month",
        "Sales": "Sales ($)"
    }
)

fig.update_layout(
    hovermode="x unified",
    xaxis_title="Month",
    yaxis_title="Sales ($)"
)

fig.show()

## Product Performance Analysis

Product-level analysis helps identify which products are contributing most to overall business performance.

I will compare products based on:

* Total sales
* Total profit
* Units sold
* Number of orders
* Average selling price

This analysis can help management identify high-performing products, products with strong profitability, and products that may require further investigation.

In [16]:
# ============================================
# STEP 8: PRODUCT PERFORMANCE
# ============================================

product_performance = (
    clean_sales
    .groupby("Product", as_index=False)
    .agg(
        Sales=("Sales", "sum"),
        Profit=("Profit", "sum"),
        Units_Sold=("Quantity", "sum"),
        Orders=("Order_ID", "nunique")
    )
)

# Calculate profit margin
product_performance["Profit_Margin"] = (
    product_performance["Profit"]
    / product_performance["Sales"]
)

# Sort by sales
product_performance = product_performance.sort_values(
    "Sales",
    ascending=False
)

display(product_performance)

,Product,Sales,Profit,Units_Sold,Orders,Profit_Margin
3,Laptop Pro 14,1898033.85,599552.95,1547,603,0.315881
9,Standing Desk,1121510.55,352619.10,1701,669,0.314414
10,Tablet 11,803689.40,252930.93,1706,671,0.314712
6,Office Chair,713577.15,222003.53,1764,697,0.311114
7,Office Monitor 27,507184.25,156882.56,1530,633,0.309321
13,Wireless Headphones,270236.30,83823.55,1598,630,0.310186
11,USB-C Dock,261300.60,80759.80,1736,680,0.309069
4,Mechanical Keyboard,196202.55,61792.64,1610,649,0.314943
12,Webcam HD,165013.20,52630.75,1762,696,0.318949
1,Desk Lamp,144878.65,45287.41,1723,672,0.312589
2,Ink Cartridge,129149.20,39600.79,1732,670,0.306628
0,Backpack,128078.75,39809.44,1717,683,0.310820
14,Wireless Mouse,77390.60,24631.41,1679,658,0.318274
8,Printer Paper,65640.90,20765.56,1781,679,0.316351
5,Notebook Pack,39976.80,12678.72,1763,688,0.317152

In [17]:
# ============================================
# TOP PRODUCTS BY SALES
# ============================================

fig = px.bar(
    product_performance.sort_values("Sales"),
    x="Sales",
    y="Product",
    orientation="h",
    title="Product Performance — Total Sales",
    labels={
        "Sales": "Total Sales ($)",
        "Product": "Product"
    },
    hover_data=[
        "Profit",
        "Units_Sold",
        "Orders",
        "Profit_Margin"
    ]
)

fig.update_layout(
    xaxis_title="Total Sales ($)",
    yaxis_title="Product"
)

fig.show()

## Product Profitability

Revenue is only one measure of business performance.

A product may generate substantial sales while producing a relatively small profit because of its underlying cost structure or discounts.

Therefore, I will compare products based on total profit as well as profit margin.

This provides a more complete view of product performance and helps distinguish products that generate revenue from products that generate profitable revenue.

In [18]:
# ============================================
# PRODUCT PROFITABILITY
# ============================================

fig = px.bar(
    product_performance.sort_values("Profit"),
    x="Profit",
    y="Product",
    orientation="h",
    title="Product Profitability — Total Profit",
    labels={
        "Profit": "Total Profit ($)",
        "Product": "Product"
    },
    hover_data=[
        "Sales",
        "Profit_Margin",
        "Units_Sold",
        "Orders"
    ]
)

fig.update_layout(
    xaxis_title="Total Profit ($)",
    yaxis_title="Product"
)

fig.show()

## Category Performance

Product categories provide a higher-level view of the business.

Aggregating transactions by category makes it easier to identify which areas of the product portfolio contribute most to revenue and profitability.

The analysis will compare:

* Total sales
* Total profit
* Units sold
* Number of orders
* Profit margin

This can support decisions related to inventory, promotions and product strategy.

In [19]:
# ============================================
# CATEGORY PERFORMANCE
# ============================================

category_performance = (
    clean_sales
    .groupby("Category", as_index=False)
    .agg(
        Sales=("Sales", "sum"),
        Profit=("Profit", "sum"),
        Units_Sold=("Quantity", "sum"),
        Orders=("Order_ID", "nunique")
    )
)

category_performance["Profit_Margin"] = (
    category_performance["Profit"]
    / category_performance["Sales"]
)

category_performance = category_performance.sort_values(
    "Sales",
    ascending=False
)

display(category_performance)

          Category       Sales      Profit  Units_Sold  Orders  Profit_Margin
1      Electronics  3644157.00  1145820.74        8143    3233       0.314427
2        Furniture  1979966.35   619910.04        5188    2038       0.313091
0      Accessories   662972.50   206993.29        6742    2670       0.312220
3  Office Supplies   234766.90    73045.07        5276    2037       0.311139

In [20]:
# ============================================
# CATEGORY SALES VS PROFIT
# ============================================

fig = px.bar(
    category_performance,
    x="Category",
    y=["Sales", "Profit"],
    barmode="group",
    title="Sales and Profit by Product Category",
    labels={
        "value": "Amount ($)",
        "variable": "Metric"
    },
    hover_data=[
        "Units_Sold",
        "Orders",
        "Profit_Margin"
    ]
)

fig.update_layout(
    xaxis_title="Product Category",
    yaxis_title="Amount ($)"
)

fig.show()

In [21]:
display(product_performance)
display(category_performance)

,Product,Sales,Profit,Units_Sold,Orders,Profit_Margin
3,Laptop Pro 14,1898033.85,599552.95,1547,603,0.315881
9,Standing Desk,1121510.55,352619.10,1701,669,0.314414
10,Tablet 11,803689.40,252930.93,1706,671,0.314712
6,Office Chair,713577.15,222003.53,1764,697,0.311114
7,Office Monitor 27,507184.25,156882.56,1530,633,0.309321
13,Wireless Headphones,270236.30,83823.55,1598,630,0.310186
11,USB-C Dock,261300.60,80759.80,1736,680,0.309069
4,Mechanical Keyboard,196202.55,61792.64,1610,649,0.314943
12,Webcam HD,165013.20,52630.75,1762,696,0.318949
1,Desk Lamp,144878.65,45287.41,1723,672,0.312589
2,Ink Cartridge,129149.20,39600.79,1732,670,0.306628
0,Backpack,128078.75,39809.44,1717,683,0.310820
14,Wireless Mouse,77390.60,24631.41,1679,658,0.318274
8,Printer Paper,65640.90,20765.56,1781,679,0.316351
5,Notebook Pack,39976.80,12678.72,1763,688,0.317152

          Category       Sales      Profit  Units_Sold  Orders  Profit_Margin
1      Electronics  3644157.00  1145820.74        8143    3233       0.314427
2        Furniture  1979966.35   619910.04        5188    2038       0.313091
0      Accessories   662972.50   206993.29        6742    2670       0.312220
3  Office Supplies   234766.90    73045.07        5276    2037       0.311139

## Geographic Performance Analysis

Geographic analysis helps identify where business activity is concentrated.

I will analyze sales and profitability at both the **provincial** and **city** levels.

The analysis will compare:

* Total sales
* Total profit
* Number of orders
* Units sold
* Profit margin

Understanding geographic performance can help management identify strong markets and areas that may require additional attention.

In [22]:
# ============================================
# STEP 11: GEOGRAPHIC ANALYSIS
# PART 1 — PROVINCE PERFORMANCE
# ============================================

province_performance = (
    clean_sales
    .groupby("Province", as_index=False)
    .agg(
        Sales=("Sales", "sum"),
        Profit=("Profit", "sum"),
        Orders=("Order_ID", "nunique"),
        Units_Sold=("Quantity", "sum")
    )
)

province_performance["Profit_Margin"] = (
    province_performance["Profit"]
    / province_performance["Sales"]
)

province_performance = province_performance.sort_values(
    "Sales",
    ascending=False
)

display(province_performance)

           Province       Sales     Profit  Orders  Units_Sold  Profit_Margin
3           Ontario  2088460.85  652193.95    3209        8158       0.312284
0           Alberta  1935178.55  608724.36    2946        7491       0.314557
1  British Columbia  1229547.00  383743.51    1807        4601       0.312102
2          Manitoba   662237.35  208043.33    1004        2539       0.314152
4      Saskatchewan   606439.00  193063.99    1012        2560       0.318357

In [23]:
# ============================================
# SALES BY PROVINCE
# ============================================

fig = px.bar(
    province_performance.sort_values("Sales"),
    x="Sales",
    y="Province",
    orientation="h",
    title="Sales by Province",
    labels={
        "Sales": "Total Sales ($)",
        "Province": "Province"
    },
    hover_data=[
        "Profit",
        "Orders",
        "Units_Sold",
        "Profit_Margin"
    ]
)

fig.update_layout(
    xaxis_title="Total Sales ($)",
    yaxis_title="Province"
)

fig.show()

## City-Level Performance

Provincial performance can hide important differences between individual markets.

To identify these differences, I will analyze sales performance at the city level.

This analysis will help identify the strongest individual markets based on sales, profit and order activity.

In [24]:
# ============================================
# CITY PERFORMANCE
# ============================================

city_performance = (
    clean_sales
    .groupby(
        ["Province", "City"],
        as_index=False
    )
    .agg(
        Sales=("Sales", "sum"),
        Profit=("Profit", "sum"),
        Orders=("Order_ID", "nunique"),
        Units_Sold=("Quantity", "sum")
    )
)

city_performance["Profit_Margin"] = (
    city_performance["Profit"]
    / city_performance["Sales"]
)

city_performance = city_performance.sort_values(
    "Sales",
    ascending=False
)

display(city_performance.head(15))

,Province,City,Sales,Profit,Orders,Units_Sold,Profit_Margin
16,Ontario,Toronto,562058.20,176794.83,815,2186,0.314549
14,Ontario,Mississauga,523560.35,161451.20,800,1972,0.308372
1,Alberta,Edmonton,513825.05,164711.18,726,1882,0.320559
15,Ontario,Ottawa,497111.80,156365.24,764,1932,0.314547
13,Ontario,Hamilton,493896.55,154422.45,810,2019,0.312662
2,Alberta,Lethbridge,492473.25,154507.07,750,1944,0.313737
3,Alberta,Red Deer,465729.80,145806.50,762,1924,0.313071
0,Alberta,Calgary,451534.75,139904.33,698,1708,0.309842
8,British Columbia,Vancouver,349425.40,106834.52,501,1303,0.305743
10,Manitoba,Brandon,339246.00,106551.44,485,1250,0.314083
18,Saskatchewan,Regina,321703.45,104760.03,514,1307,0.325642
12,Manitoba,Winnipeg,316203.65,99443.36,511,1270,0.314491
5,British Columbia,Kelowna,312757.05,100266.53,437,1086,0.320589
6,British Columbia,Surrey,283623.35,90414.55,419,1131,0.318784
19,Saskatchewan,Saskatoon,282672.15,87656.92,490,1233,0.310101

In [25]:
# ============================================
# TOP 15 CITIES BY SALES
# ============================================

top_cities = (
    city_performance
    .sort_values("Sales", ascending=False)
    .head(15)
    .sort_values("Sales")
)

fig = px.bar(
    top_cities,
    x="Sales",
    y="City",
    orientation="h",
    title="Top 15 Cities by Sales",
    labels={
        "Sales": "Total Sales ($)",
        "City": "City"
    },
    hover_data=[
        "Province",
        "Profit",
        "Orders",
        "Units_Sold",
        "Profit_Margin"
    ]
)

fig.update_layout(
    xaxis_title="Total Sales ($)",
    yaxis_title="City"
)

fig.show()

In [26]:
display(province_performance)
display(city_performance.head(15))

           Province       Sales     Profit  Orders  Units_Sold  Profit_Margin
3           Ontario  2088460.85  652193.95    3209        8158       0.312284
0           Alberta  1935178.55  608724.36    2946        7491       0.314557
1  British Columbia  1229547.00  383743.51    1807        4601       0.312102
2          Manitoba   662237.35  208043.33    1004        2539       0.314152
4      Saskatchewan   606439.00  193063.99    1012        2560       0.318357

,Province,City,Sales,Profit,Orders,Units_Sold,Profit_Margin
16,Ontario,Toronto,562058.20,176794.83,815,2186,0.314549
14,Ontario,Mississauga,523560.35,161451.20,800,1972,0.308372
1,Alberta,Edmonton,513825.05,164711.18,726,1882,0.320559
15,Ontario,Ottawa,497111.80,156365.24,764,1932,0.314547
13,Ontario,Hamilton,493896.55,154422.45,810,2019,0.312662
2,Alberta,Lethbridge,492473.25,154507.07,750,1944,0.313737
3,Alberta,Red Deer,465729.80,145806.50,762,1924,0.313071
0,Alberta,Calgary,451534.75,139904.33,698,1708,0.309842
8,British Columbia,Vancouver,349425.40,106834.52,501,1303,0.305743
10,Manitoba,Brandon,339246.00,106551.44,485,1250,0.314083
18,Saskatchewan,Regina,321703.45,104760.03,514,1307,0.325642
12,Manitoba,Winnipeg,316203.65,99443.36,511,1270,0.314491
5,British Columbia,Kelowna,312757.05,100266.53,437,1086,0.320589
6,British Columbia,Surrey,283623.35,90414.55,419,1131,0.318784
19,Saskatchewan,Saskatoon,282672.15,87656.92,490,1233,0.310101

## Sales Channel Analysis

Sales channels can have different levels of customer activity, revenue and profitability.

This analysis compares the performance of each sales channel using:

* Total sales
* Total profit
* Number of orders
* Units sold
* Average order value
* Profit margin

The objective is to determine which channels contribute most to overall business performance and whether differences exist between sales volume and profitability.

In [27]:
# ============================================
# STEP 13: SALES CHANNEL ANALYSIS
# ============================================

channel_performance = (
    clean_sales
    .groupby("Sales_Channel", as_index=False)
    .agg(
        Sales=("Sales", "sum"),
        Profit=("Profit", "sum"),
        Orders=("Order_ID", "nunique"),
        Units_Sold=("Quantity", "sum")
    )
)

channel_performance["Average_Order_Value"] = (
    channel_performance["Sales"]
    / channel_performance["Orders"]
)

channel_performance["Profit_Margin"] = (
    channel_performance["Profit"]
    / channel_performance["Sales"]
)

channel_performance = channel_performance.sort_values(
    "Sales",
    ascending=False
)

display(channel_performance)

,Sales_Channel,Sales,Profit,Orders,Units_Sold,Average_Order_Value,Profit_Margin
0,Online,3502977.00,1097544.30,5478,13860,639.462760,0.313318
1,Retail Store,1995613.10,629716.00,3040,7670,656.451678,0.315550
2,Wholesale,1023272.65,318508.84,1460,3819,700.871678,0.311265

In [28]:
# ============================================
# SALES BY CHANNEL
# ============================================

fig = px.bar(
    channel_performance,
    x="Sales_Channel",
    y="Sales",
    title="Sales Performance by Sales Channel",
    labels={
        "Sales_Channel": "Sales Channel",
        "Sales": "Total Sales ($)"
    },
    hover_data=[
        "Profit",
        "Orders",
        "Units_Sold",
        "Average_Order_Value",
        "Profit_Margin"
    ]
)

fig.update_layout(
    xaxis_title="Sales Channel",
    yaxis_title="Total Sales ($)"
)

fig.show()

In [29]:
# ============================================
# PROFIT BY SALES CHANNEL
# ============================================

fig = px.bar(
    channel_performance,
    x="Sales_Channel",
    y="Profit",
    title="Profit Performance by Sales Channel",
    labels={
        "Sales_Channel": "Sales Channel",
        "Profit": "Total Profit ($)"
    },
    hover_data=[
        "Sales",
        "Orders",
        "Units_Sold",
        "Average_Order_Value",
        "Profit_Margin"
    ]
)

fig.update_layout(
    xaxis_title="Sales Channel",
    yaxis_title="Total Profit ($)"
)

fig.show()

## Discount and Profitability Analysis

Discounting can help increase sales volume, but excessive discounts may reduce profitability.

To investigate this relationship, I will compare transactions across different discount levels.

The analysis will examine:

* Sales
* Profit
* Profit margin
* Number of orders
* Units sold

This will help determine whether higher discounts appear to be associated with changes in profitability.

In [30]:
# ============================================
# STEP 14: DISCOUNT ANALYSIS
# ============================================

discount_performance = (
    clean_sales
    .groupby("Discount", as_index=False)
    .agg(
        Sales=("Sales", "sum"),
        Profit=("Profit", "sum"),
        Orders=("Order_ID", "nunique"),
        Units_Sold=("Quantity", "sum")
    )
)

discount_performance["Profit_Margin"] = (
    discount_performance["Profit"]
    / discount_performance["Sales"]
)

discount_performance["Discount_Percentage"] = (
    discount_performance["Discount"] * 100
)

display(discount_performance)

,Discount,Sales,Profit,Orders,Units_Sold,Profit_Margin,Discount_Percentage
0,0.00,3127089.00,985459.10,4447,11306,0.315136,0.0
1,0.05,1300176.65,403344.27,2036,5238,0.310223,5.0
2,0.10,1188012.60,371174.31,1947,4866,0.312433,10.0
3,0.15,602678.90,190959.82,1035,2661,0.316852,15.0
4,0.20,303905.60,94831.64,513,1278,0.312043,20.0

In [31]:
# ============================================
# DISCOUNT VS PROFIT MARGIN
# ============================================

fig = px.bar(
    discount_performance,
    x="Discount_Percentage",
    y="Profit_Margin",
    title="Profit Margin by Discount Level",
    labels={
        "Discount_Percentage": "Discount (%)",
        "Profit_Margin": "Profit Margin"
    },
    hover_data=[
        "Sales",
        "Profit",
        "Orders",
        "Units_Sold"
    ]
)

fig.update_yaxes(
    tickformat=".1%"
)

fig.show()

In [32]:
display(channel_performance)
display(discount_performance)

,Sales_Channel,Sales,Profit,Orders,Units_Sold,Average_Order_Value,Profit_Margin
0,Online,3502977.00,1097544.30,5478,13860,639.462760,0.313318
1,Retail Store,1995613.10,629716.00,3040,7670,656.451678,0.315550
2,Wholesale,1023272.65,318508.84,1460,3819,700.871678,0.311265

,Discount,Sales,Profit,Orders,Units_Sold,Profit_Margin,Discount_Percentage
0,0.00,3127089.00,985459.10,4447,11306,0.315136,0.0
1,0.05,1300176.65,403344.27,2036,5238,0.310223,5.0
2,0.10,1188012.60,371174.31,1947,4866,0.312433,10.0
3,0.15,602678.90,190959.82,1035,2661,0.316852,15.0
4,0.20,303905.60,94831.64,513,1278,0.312043,20.0

## 5. Interactive Business Explorer

To make the analysis more useful for decision-making, I will create an interactive business explorer.

Users will be able to filter the dataset by:

* Province
* Product Category
* Sales Channel

The filtered results will update key performance indicators and visualizations.

This approach demonstrates how Python can be used not only for analysis, but also to create interactive analytical tools that allow users to explore business data without manually modifying the underlying dataset.

In [35]:
# ============================================
# STEP 15: INTERACTIVE BUSINESS EXPLORER
# COLAB VERSION
# ============================================

import ipywidgets as widgets
from IPython.display import display, clear_output


# --------------------------------------------
# FILTER OPTIONS
# --------------------------------------------

province_options = ["All"] + sorted(
    clean_sales["Province"].dropna().unique().tolist()
)

category_options = ["All"] + sorted(
    clean_sales["Category"].dropna().unique().tolist()
)

channel_options = ["All"] + sorted(
    clean_sales["Sales_Channel"].dropna().unique().tolist()
)


# --------------------------------------------
# CREATE DROPDOWNS
# --------------------------------------------

province_dropdown = widgets.Dropdown(
    options=province_options,
    value="All",
    description="Province:"
)

category_dropdown = widgets.Dropdown(
    options=category_options,
    value="All",
    description="Category:"
)

channel_dropdown = widgets.Dropdown(
    options=channel_options,
    value="All",
    description="Channel:"
)


# --------------------------------------------
# OUTPUT AREA
# --------------------------------------------

output = widgets.Output()


# --------------------------------------------
# DASHBOARD FUNCTION
# --------------------------------------------

def update_dashboard(change=None):

    # Get current filter selections
    province = province_dropdown.value
    category = category_dropdown.value
    channel = channel_dropdown.value

    filtered = clean_sales.copy()

    # Apply Province filter
    if province != "All":
        filtered = filtered[
            filtered["Province"] == province
        ]

    # Apply Category filter
    if category != "All":
        filtered = filtered[
            filtered["Category"] == category
        ]

    # Apply Channel filter
    if channel != "All":
        filtered = filtered[
            filtered["Sales_Channel"] == channel
        ]

    # ----------------------------------------
    # CLEAR PREVIOUS OUTPUT
    # ----------------------------------------

    with output:

        clear_output(wait=True)

        # ------------------------------------
        # Check whether data exists
        # ------------------------------------

        if filtered.empty:

            print("No transactions match the selected filters.")

            return

        # ------------------------------------
        # KPI CALCULATIONS
        # ------------------------------------

        total_sales = filtered["Sales"].sum()

        total_profit = filtered["Profit"].sum()

        total_orders = filtered["Order_ID"].nunique()

        total_units = filtered["Quantity"].sum()

        average_order_value = (
            total_sales / total_orders
        )

        profit_margin = (
            total_profit / total_sales
        )

        # ------------------------------------
        # DISPLAY FILTER SELECTION
        # ------------------------------------

        print("=" * 65)
        print("INTERACTIVE BUSINESS EXPLORER")
        print("=" * 65)

        print(
            f"\nFilters:"
            f"\nProvince: {province}"
            f"\nCategory: {category}"
            f"\nChannel: {channel}"
        )

        print("\n" + "-" * 65)

        # ------------------------------------
        # DISPLAY KPIs
        # ------------------------------------

        print(f"Total Sales:         ${total_sales:,.2f}")
        print(f"Total Profit:        ${total_profit:,.2f}")
        print(f"Total Orders:        {total_orders:,}")
        print(f"Units Sold:          {total_units:,}")
        print(f"Average Order Value: ${average_order_value:,.2f}")
        print(f"Profit Margin:       {profit_margin:.2%}")

        print("\n" + "-" * 65)

        # ------------------------------------
        # PRODUCT PERFORMANCE
        # ------------------------------------

        product_summary = (
            filtered
            .groupby("Product", as_index=False)
            .agg(
                Sales=("Sales", "sum"),
                Profit=("Profit", "sum")
            )
            .sort_values(
                "Sales",
                ascending=False
            )
            .head(10)
        )

        fig1 = px.bar(
            product_summary.sort_values("Sales"),
            x="Sales",
            y="Product",
            orientation="h",
            title="Top Products by Sales",
            labels={
                "Sales": "Sales ($)",
                "Product": "Product"
            }
        )

        fig1.show()

        # ------------------------------------
        # MONTHLY PERFORMANCE
        # ------------------------------------

        monthly = (
            filtered
            .groupby("Month", as_index=False)
            .agg(
                Sales=("Sales", "sum"),
                Profit=("Profit", "sum")
            )
        )

        fig2 = px.line(
            monthly,
            x="Month",
            y=["Sales", "Profit"],
            markers=True,
            title="Monthly Sales and Profit",
            labels={
                "value": "Amount ($)",
                "Month": "Month",
                "variable": "Metric"
            }
        )

        fig2.update_layout(
            hovermode="x unified"
        )

        fig2.show()

        # ------------------------------------
        # SHOW FILTERED DATA SAMPLE
        # ------------------------------------

        print("\nFiltered Transaction Sample:")

        display(
            filtered[
                [
                    "Order_ID",
                    "Order_Date",
                    "Province",
                    "City",
                    "Product",
                    "Category",
                    "Sales",
                    "Profit",
                    "Sales_Channel"
                ]
            ].head(10)
        )


# --------------------------------------------
# CONNECT DROPDOWNS TO FUNCTION
# --------------------------------------------

province_dropdown.observe(
    update_dashboard,
    names="value"
)

category_dropdown.observe(
    update_dashboard,
    names="value"
)

channel_dropdown.observe(
    update_dashboard,
    names="value"
)


# --------------------------------------------
# DISPLAY FILTERS
# --------------------------------------------

display(
    widgets.VBox([
        province_dropdown,
        category_dropdown,
        channel_dropdown
    ])
)

display(output)


# --------------------------------------------
# RUN INITIAL DASHBOARD
# --------------------------------------------

update_dashboard()

VBox(children=(Dropdown(description='Province:', options=('All', 'Alberta', 'British Columbia', 'Manitoba', 'O…

Output()

## Customer and Order Analysis

Understanding customer and order behavior provides another perspective on business performance.

In addition to revenue and profit, I will examine:

* Number of unique customers
* Orders per customer
* Average order value
* Customer revenue contribution
* Repeat customer activity

This analysis can help identify whether sales are primarily generated through a broad customer base or concentrated among a smaller group of customers.

In [36]:
# ============================================
# STEP 16: CUSTOMER & ORDER ANALYSIS
# ============================================

# --------------------------------------------
# Customer-level summary
# --------------------------------------------

customer_performance = (
    clean_sales
    .groupby("Customer_ID", as_index=False)
    .agg(
        Orders=("Order_ID", "nunique"),
        Sales=("Sales", "sum"),
        Profit=("Profit", "sum"),
        Units_Sold=("Quantity", "sum")
    )
)

customer_performance["Average_Order_Value"] = (
    customer_performance["Sales"]
    / customer_performance["Orders"]
)

customer_performance = customer_performance.sort_values(
    "Sales",
    ascending=False
)

# --------------------------------------------
# Customer KPIs
# --------------------------------------------

unique_customers = clean_sales["Customer_ID"].nunique()

repeat_customers = (
    customer_performance["Orders"] > 1
).sum()

one_time_customers = (
    customer_performance["Orders"] == 1
).sum()

repeat_customer_rate = (
    repeat_customers / unique_customers
)

print("CUSTOMER ANALYSIS")
print("=" * 50)

print(f"Unique Customers:       {unique_customers:,}")
print(f"Repeat Customers:       {repeat_customers:,}")
print(f"One-Time Customers:     {one_time_customers:,}")
print(f"Repeat Customer Rate:   {repeat_customer_rate:.2%}")

print("\nTop 10 Customers by Sales:")

display(
    customer_performance.head(10)
)

CUSTOMER ANALYSIS
==================================================
Unique Customers:       3,038
Repeat Customers:       2,604
One-Time Customers:     434
Repeat Customer Rate:   85.71%

Top 10 Customers by Sales:

     Customer_ID  Orders     Sales   Profit  Units_Sold  Average_Order_Value
428    CUST-1453       5  15296.10  5316.76          21          3059.220000
314    CUST-1333       6  15244.30  5382.79          22          2540.716667
1000   CUST-2056       6  14601.05  5939.08          17          2433.508333
17     CUST-1018       6  13328.75  3425.55          20          2221.458333
456    CUST-1484       9  13184.90  5032.13          22          1464.988889
1527   CUST-2608       3  13153.90  3960.74          14          4384.633333
2944   CUST-4101       7  12823.15  4360.63          22          1831.878571
2943   CUST-4100       6  12789.90  3338.02          19          2131.650000
1882   CUST-2984       5  12066.00  3468.99          23          2413.200000
1137   CUST-2201       7  12044.80  3310.45          23          1720.685714

In [37]:
# ============================================
# TOP 10 CUSTOMERS BY SALES
# ============================================

top_customers = (
    customer_performance
    .head(10)
    .sort_values("Sales")
)

fig = px.bar(
    top_customers,
    x="Sales",
    y="Customer_ID",
    orientation="h",
    title="Top 10 Customers by Sales",
    labels={
        "Sales": "Total Sales ($)",
        "Customer_ID": "Customer"
    },
    hover_data=[
        "Orders",
        "Profit",
        "Units_Sold",
        "Average_Order_Value"
    ]
)

fig.update_layout(
    xaxis_title="Total Sales ($)",
    yaxis_title="Customer"
)

fig.show()

## Management Insights and Recommendations

The analysis has now covered overall performance, products, categories, geography, sales channels, discounts, and customer behavior.

The next step is to translate these findings into practical business insights.

### Key Areas of Focus

- Revenue and profit performance
- Product and category performance
- Geographic performance
- Sales channel performance
- Customer retention
- Discount strategy

The goal is to move beyond describing the data and identify actions that could help management improve sales, profitability, and customer retention.

In [38]:
# ============================================
# STEP 17: MANAGEMENT INSIGHTS
# ============================================

# Overall business KPIs
total_sales = clean_sales["Sales"].sum()
total_profit = clean_sales["Profit"].sum()
total_orders = clean_sales["Order_ID"].nunique()
total_units = clean_sales["Quantity"].sum()

average_order_value = total_sales / total_orders
overall_profit_margin = total_profit / total_sales

# Top performers
top_product = product_performance.iloc[0]
top_category = category_performance.iloc[0]
top_province = province_performance.iloc[0]
top_channel = channel_performance.sort_values(
    "Sales", ascending=False
).iloc[0]

# Highest margin performers
highest_margin_product = product_performance.sort_values(
    "Profit_Margin", ascending=False
).iloc[0]

highest_margin_province = province_performance.sort_values(
    "Profit_Margin", ascending=False
).iloc[0]

highest_margin_channel = channel_performance.sort_values(
    "Profit_Margin", ascending=False
).iloc[0]

print("=" * 70)
print("MANAGEMENT INSIGHTS")
print("=" * 70)

print("\n1. OVERALL BUSINESS PERFORMANCE")
print("-" * 70)
print(f"Total Sales:          ${total_sales:,.2f}")
print(f"Total Profit:         ${total_profit:,.2f}")
print(f"Total Orders:         {total_orders:,}")
print(f"Units Sold:           {total_units:,}")
print(f"Average Order Value:  ${average_order_value:,.2f}")
print(f"Overall Profit Margin:{overall_profit_margin:>8.2%}")

print("\n2. PRODUCT PERFORMANCE")
print("-" * 70)
print(
    f"Top product by sales: {top_product['Product']} "
    f"(${top_product['Sales']:,.2f})"
)
print(
    f"Highest-margin product: {highest_margin_product['Product']} "
    f"({highest_margin_product['Profit_Margin']:.2%})"
)

print("\n3. CATEGORY PERFORMANCE")
print("-" * 70)
print(
    f"Top category: {top_category['Category']} "
    f"(${top_category['Sales']:,.2f})"
)

print("\n4. GEOGRAPHIC PERFORMANCE")
print("-" * 70)
print(
    f"Top province by sales: {top_province['Province']} "
    f"(${top_province['Sales']:,.2f})"
)
print(
    f"Highest-margin province: {highest_margin_province['Province']} "
    f"({highest_margin_province['Profit_Margin']:.2%})"
)

print("\n5. SALES CHANNEL PERFORMANCE")
print("-" * 70)
print(
    f"Top channel by sales: {top_channel['Sales_Channel']} "
    f"(${top_channel['Sales']:,.2f})"
)
print(
    f"Highest-margin channel: {highest_margin_channel['Sales_Channel']} "
    f"({highest_margin_channel['Profit_Margin']:.2%})"
)

print("\n6. CUSTOMER PERFORMANCE")
print("-" * 70)
print(f"Unique customers:       {unique_customers:,}")
print(f"Repeat customers:       {repeat_customers:,}")
print(f"Repeat customer rate:   {repeat_customer_rate:.2%}")

print("\n" + "=" * 70)
print("RECOMMENDATIONS")
print("=" * 70)

print("""
1. Protect high-performing products
   Focus inventory and marketing efforts on products generating the
   strongest revenue and profit contribution.

2. Maintain strong customer retention
   The high repeat-customer rate suggests that customer retention is
   an important strength of the business.

3. Monitor geographic opportunities
   Continue supporting high-performing provinces while investigating
   lower-performing markets for growth opportunities.

4. Evaluate sales channels separately
   Sales volume and profitability differ by channel, so management
   should avoid using a single strategy across all channels.

5. Review discount strategy
   Discounts should be evaluated based on both sales volume and
   profitability rather than assuming that larger discounts always
   produce better results.

6. Identify high-value customers
   Customers with high sales and repeat purchases could be targeted
   with loyalty programs, personalized offers, and retention campaigns.
""")

======================================================================
MANAGEMENT INSIGHTS
======================================================================

1. OVERALL BUSINESS PERFORMANCE
----------------------------------------------------------------------
Total Sales:          $6,521,862.75
Total Profit:         $2,045,769.14
Total Orders:         9,978
Units Sold:           25,349
Average Order Value:  $653.62
Overall Profit Margin:  31.37%

2. PRODUCT PERFORMANCE
----------------------------------------------------------------------
Top product by sales: Laptop Pro 14 ($1,898,033.85)
Highest-margin product: Webcam HD (31.89%)

3. CATEGORY PERFORMANCE
----------------------------------------------------------------------
Top category: Electronics ($3,644,157.00)

4. GEOGRAPHIC PERFORMANCE
----------------------------------------------------------------------
Top province by sales: Ontario ($2,088,460.85)
Highest-margin province: Saskatchewan (31.84%)

5. SALES CHANNEL PERFORMANCE
----------------------------------------------------------------------
Top channel by sales: Online ($3,502,977.00)
Highest-margin channel: Retail Store (31.56%)

6. CUSTOMER PERFORMANCE
----------------------------------------------------------------------
Unique customers:       3,038
Repeat customers:       2,604
Repeat customer rate:   85.71%

======================================================================
RECOMMENDATIONS
======================================================================

1. Protect high-performing products
   Focus inventory and marketing efforts on products generating the
   strongest revenue and profit contribution.

2. Maintain strong customer retention
   The high repeat-customer rate suggests that customer retention is
   an important strength of the business.

3. Monitor geographic opportunities
   Continue supporting high-performing provinces while investigating
   lower-performing markets for growth opportunities.

4. Evaluate sales channels separately
   Sales volume and profitability differ by channel, so management
   should avoid using a single strategy across all channels.

5. Review discount strategy
   Discounts should be evaluated based on both sales volume and
   profitability rather than assuming that larger discounts always
   produce better results.

6. Identify high-value customers
   Customers with high sales and repeat purchases could be targeted
   with loyalty programs, personalized offers, and retention campaigns.

## Executive KPI Dashboard

The following KPIs provide management with a high-level view of business performance.

These metrics summarize revenue, profitability, transaction volume, customer value, and customer retention.

### Key Performance Indicators

- **Total Sales:** Overall revenue generated
- **Total Profit:** Profit generated after costs
- **Total Orders:** Number of unique transactions
- **Average Order Value:** Average revenue generated per order
- **Profit Margin:** Percentage of sales retained as profit
- **Repeat Customer Rate:** Percentage of customers who made more than one purchase

These KPIs provide a concise starting point before management moves into more detailed analysis.

In [39]:
# ============================================
# STEP 18: EXECUTIVE KPI DASHBOARD
# ============================================

# Calculate executive KPIs

kpi_sales = clean_sales["Sales"].sum()
kpi_profit = clean_sales["Profit"].sum()
kpi_orders = clean_sales["Order_ID"].nunique()
kpi_aov = kpi_sales / kpi_orders
kpi_margin = kpi_profit / kpi_sales

kpi_customers = clean_sales["Customer_ID"].nunique()

kpi_repeat_customers = (
    clean_sales
    .groupby("Customer_ID")["Order_ID"]
    .nunique()
    .gt(1)
    .sum()
)

kpi_repeat_rate = kpi_repeat_customers / kpi_customers


# Display KPIs
print("=" * 75)
print("EXECUTIVE KPI DASHBOARD")
print("=" * 75)

print(f"\nTotal Sales:           ${kpi_sales:,.2f}")
print(f"Total Profit:          ${kpi_profit:,.2f}")
print(f"Total Orders:          {kpi_orders:,}")
print(f"Average Order Value:   ${kpi_aov:,.2f}")
print(f"Profit Margin:         {kpi_margin:.2%}")
print(f"Repeat Customer Rate:  {kpi_repeat_rate:.2%}")

print("\n" + "=" * 75)

===========================================================================
EXECUTIVE KPI DASHBOARD
===========================================================================

Total Sales:           $6,521,862.75
Total Profit:          $2,045,769.14
Total Orders:          9,978
Average Order Value:   $653.62
Profit Margin:         31.37%
Repeat Customer Rate:  85.71%

===========================================================================

## Interactive Management Dashboard

This dashboard brings the analysis together into an interactive management view.

The objective is to allow decision-makers to quickly examine:

- Revenue and profit trends
- Product performance
- Category performance
- Geographic performance
- Sales channel performance

Interactive filtering allows management to investigate specific segments of the business rather than relying only on overall totals.

In [40]:
# ============================================
# STEP 19: INTERACTIVE MANAGEMENT DASHBOARD
# ============================================

import plotly.express as px
import ipywidgets as widgets
from IPython.display import display, clear_output


# --------------------------------------------
# FILTER OPTIONS
# --------------------------------------------

province_options = ["All"] + sorted(
    clean_sales["Province"].unique().tolist()
)

category_options = ["All"] + sorted(
    clean_sales["Category"].unique().tolist()
)

channel_options = ["All"] + sorted(
    clean_sales["Sales_Channel"].unique().tolist()
)


# --------------------------------------------
# CREATE FILTERS
# --------------------------------------------

province_filter = widgets.Dropdown(
    options=province_options,
    value="All",
    description="Province:"
)

category_filter = widgets.Dropdown(
    options=category_options,
    value="All",
    description="Category:"
)

channel_filter = widgets.Dropdown(
    options=channel_options,
    value="All",
    description="Channel:"
)

dashboard_output = widgets.Output()


# --------------------------------------------
# DASHBOARD FUNCTION
# --------------------------------------------

def update_management_dashboard(change=None):

    province = province_filter.value
    category = category_filter.value
    channel = channel_filter.value

    filtered = clean_sales.copy()

    # Apply filters
    if province != "All":
        filtered = filtered[
            filtered["Province"] == province
        ]

    if category != "All":
        filtered = filtered[
            filtered["Category"] == category
        ]

    if channel != "All":
        filtered = filtered[
            filtered["Sales_Channel"] == channel
        ]

    with dashboard_output:

        clear_output(wait=True)

        if filtered.empty:
            print("No data matches the selected filters.")
            return

        # ------------------------------------
        # KPI CALCULATIONS
        # ------------------------------------

        sales = filtered["Sales"].sum()
        profit = filtered["Profit"].sum()
        orders = filtered["Order_ID"].nunique()
        units = filtered["Quantity"].sum()

        aov = sales / orders
        margin = profit / sales

        # ------------------------------------
        # KPI DISPLAY
        # ------------------------------------

        print("=" * 80)
        print("INTERACTIVE MANAGEMENT DASHBOARD")
        print("=" * 80)

        print(
            f"\nFilters:"
            f"\nProvince: {province}"
            f"\nCategory: {category}"
            f"\nChannel: {channel}"
        )

        print("\n" + "-" * 80)

        print(f"Total Sales:          ${sales:,.2f}")
        print(f"Total Profit:         ${profit:,.2f}")
        print(f"Total Orders:         {orders:,}")
        print(f"Units Sold:           {units:,}")
        print(f"Average Order Value:  ${aov:,.2f}")
        print(f"Profit Margin:        {margin:.2%}")

        print("\n" + "-" * 80)


        # ------------------------------------
        # MONTHLY PERFORMANCE
        # ------------------------------------

        monthly = (
            filtered
            .groupby("Month", as_index=False)
            .agg(
                Sales=("Sales", "sum"),
                Profit=("Profit", "sum")
            )
        )

        fig_monthly = px.line(
            monthly,
            x="Month",
            y=["Sales", "Profit"],
            markers=True,
            title="Monthly Sales and Profit",
            labels={
                "value": "Amount ($)",
                "Month": "Month",
                "variable": "Metric"
            }
        )

        fig_monthly.update_layout(
            hovermode="x unified"
        )

        fig_monthly.show()


        # ------------------------------------
        # CATEGORY PERFORMANCE
        # ------------------------------------

        category = (
            filtered
            .groupby("Category", as_index=False)
            .agg(
                Sales=("Sales", "sum"),
                Profit=("Profit", "sum")
            )
            .sort_values("Sales", ascending=True)
        )

        fig_category = px.bar(
            category,
            x="Sales",
            y="Category",
            orientation="h",
            title="Sales by Category",
            labels={
                "Sales": "Sales ($)",
                "Category": "Category"
            }
        )

        fig_category.show()


        # ------------------------------------
        # PROVINCE PERFORMANCE
        # ------------------------------------

        province = (
            filtered
            .groupby("Province", as_index=False)
            .agg(
                Sales=("Sales", "sum"),
                Profit=("Profit", "sum")
            )
            .sort_values("Sales", ascending=True)
        )

        fig_province = px.bar(
            province,
            x="Sales",
            y="Province",
            orientation="h",
            title="Sales by Province",
            labels={
                "Sales": "Sales ($)",
                "Province": "Province"
            }
        )

        fig_province.show()


        # ------------------------------------
        # SALES CHANNEL
        # ------------------------------------

        channel = (
            filtered
            .groupby("Sales_Channel", as_index=False)
            .agg(
                Sales=("Sales", "sum"),
                Profit=("Profit", "sum")
            )
            .sort_values("Sales", ascending=True)
        )

        fig_channel = px.bar(
            channel,
            x="Sales",
            y="Sales_Channel",
            orientation="h",
            title="Sales by Channel",
            labels={
                "Sales": "Sales ($)",
                "Sales_Channel": "Sales Channel"
            }
        )

        fig_channel.show()


        # ------------------------------------
        # TOP 10 PRODUCTS
        # ------------------------------------

        products = (
            filtered
            .groupby("Product", as_index=False)
            .agg(
                Sales=("Sales", "sum"),
                Profit=("Profit", "sum")
            )
            .sort_values("Sales", ascending=False)
            .head(10)
            .sort_values("Sales", ascending=True)
        )

        fig_products = px.bar(
            products,
            x="Sales",
            y="Product",
            orientation="h",
            title="Top 10 Products by Sales",
            labels={
                "Sales": "Sales ($)",
                "Product": "Product"
            },
            hover_data=["Profit"]
        )

        fig_products.show()


# --------------------------------------------
# CONNECT FILTERS TO DASHBOARD
# --------------------------------------------

province_filter.observe(
    update_management_dashboard,
    names="value"
)

category_filter.observe(
    update_management_dashboard,
    names="value"
)

channel_filter.observe(
    update_management_dashboard,
    names="value"
)


# --------------------------------------------
# DISPLAY DASHBOARD
# --------------------------------------------

display(
    widgets.HBox([
        province_filter,
        category_filter,
        channel_filter
    ])
)

display(dashboard_output)

update_management_dashboard()

HBox(children=(Dropdown(description='Province:', options=('All', 'Alberta', 'British Columbia', 'Manitoba', 'O…

Output()

## Preparing the Clean Dataset for Power BI

The cleaned dataset is now ready to be prepared for business intelligence reporting.

Before importing the data into Power BI, I will perform a final structural check and export the validated dataset as a CSV file.

This creates a reusable analytical dataset that can support:

- Power BI dashboards
- Excel reporting
- Further Python analysis
- Client reporting
- Future automated workflows

The exported dataset contains only validated and analysis-ready records.

In [41]:
# ============================================
# STEP 20: PREPARE DATASET FOR POWER BI
# ============================================

# Create final Power BI dataset
powerbi_data = clean_sales.copy()

# Arrange columns in a business-friendly order
powerbi_columns = [
    "Order_ID",
    "Order_Date",
    "Customer_ID",
    "Customer_Name",
    "Province",
    "City",
    "Product",
    "Category",
    "Quantity",
    "Unit_Price",
    "Discount",
    "Sales",
    "Cost",
    "Profit",
    "Profit_Margin",
    "Payment_Method",
    "Sales_Channel",
    "Year",
    "Month",
    "Month_Name"
]

powerbi_data = powerbi_data[powerbi_columns]

# Final structural checks
print("=" * 70)
print("POWER BI DATASET PREPARATION")
print("=" * 70)

print(f"\nRows: {len(powerbi_data):,}")
print(f"Columns: {len(powerbi_data.columns)}")

print("\nMissing Values:")
print(powerbi_data.isna().sum().sum())

print("\nDuplicate Order IDs:")
print(powerbi_data["Order_ID"].duplicated().sum())

print("\nDate Range:")
print(
    f"{powerbi_data['Order_Date'].min().date()} "
    f"to "
    f"{powerbi_data['Order_Date'].max().date()}"
)

print("\nColumn List:")
print(powerbi_data.columns.tolist())

print("\n" + "=" * 70)
print("DATASET READY FOR POWER BI")
print("=" * 70)

======================================================================
POWER BI DATASET PREPARATION
======================================================================

Rows: 9,978
Columns: 20

Missing Values:
0

Duplicate Order IDs:
0

Date Range:
2025-01-01 to 2026-06-30

Column List:
['Order_ID', 'Order_Date', 'Customer_ID', 'Customer_Name', 'Province', 'City', 'Product', 'Category', 'Quantity', 'Unit_Price', 'Discount', 'Sales', 'Cost', 'Profit', 'Profit_Margin', 'Payment_Method', 'Sales_Channel', 'Year', 'Month', 'Month_Name']

======================================================================
DATASET READY FOR POWER BI
======================================================================

In [43]:
# ============================================
# EXPORT CLEAN DATASET
# ============================================

file_name = "small_business_sales_clean.csv"

powerbi_data.to_csv(
    file_name,
    index=False
)

print(f"File created successfully: {file_name}")
print(f"Rows exported: {len(powerbi_data):,}")
print(f"Columns exported: {len(powerbi_data.columns)}")

File created successfully: small_business_sales_clean.csv
Rows exported: 9,978
Columns exported: 20

In [44]:
from google.colab import files

files.download("small_business_sales_clean.csv")

# Interactive Sales Performance Dashboard

This dashboard provides a simple interactive view of business performance.

Users can filter the data by **Province, Category, and Sales Channel** to understand how different parts of the business are performing.

### Dashboard Objectives

- Monitor sales and profitability
- Identify top-performing products
- Compare geographic performance
- Evaluate sales channels
- Understand changes in performance over time

The dashboard is designed to provide quick insights without requiring users to work directly with the underlying dataset.

In [46]:
# ============================================
# STEP 21: INTERACTIVE SALES DASHBOARD
# ============================================

import ipywidgets as widgets
from IPython.display import display, clear_output


# --------------------------------------------
# FILTERS
# --------------------------------------------

province_filter = widgets.Dropdown(
    options=["All"] + sorted(clean_sales["Province"].unique()),
    value="All",
    description="Province:"
)

category_filter = widgets.Dropdown(
    options=["All"] + sorted(clean_sales["Category"].unique()),
    value="All",
    description="Category:"
)

channel_filter = widgets.Dropdown(
    options=["All"] + sorted(clean_sales["Sales_Channel"].unique()),
    value="All",
    description="Channel:"
)

dashboard = widgets.Output()


# --------------------------------------------
# DASHBOARD FUNCTION
# --------------------------------------------

def build_dashboard(change=None):

    data = clean_sales.copy()

    # Apply Province filter
    if province_filter.value != "All":
        data = data[
            data["Province"] == province_filter.value
        ]

    # Apply Category filter
    if category_filter.value != "All":
        data = data[
            data["Category"] == category_filter.value
        ]

    # Apply Channel filter
    if channel_filter.value != "All":
        data = data[
            data["Sales_Channel"] == channel_filter.value
        ]


    with dashboard:

        clear_output(wait=True)

        if data.empty:
            print("No data available for the selected filters.")
            return


        # ------------------------------------
        # KPI CALCULATIONS
        # ------------------------------------

        sales = data["Sales"].sum()
        profit = data["Profit"].sum()
        orders = data["Order_ID"].nunique()
        aov = sales / orders
        margin = profit / sales


        # ------------------------------------
        # KPI DISPLAY
        # ------------------------------------

        print("=" * 75)
        print("SALES PERFORMANCE DASHBOARD")
        print("=" * 75)

        print(
            f"\nSales: ${sales:,.2f}"
            f"     |     Profit: ${profit:,.2f}"
        )

        print(
            f"Orders: {orders:,}"
            f"     |     Average Order Value: ${aov:,.2f}"
            f"     |     Profit Margin: {margin:.2%}"
        )

        print("\n" + "-" * 75)


        # ------------------------------------
        # 1. SALES & PROFIT TREND
        # ------------------------------------

        monthly = (
            data
            .groupby("Month", as_index=False)
            .agg(
                Sales=("Sales", "sum"),
                Profit=("Profit", "sum")
            )
        )

        fig1 = px.line(
            monthly,
            x="Month",
            y=["Sales", "Profit"],
            markers=True,
            title="Sales and Profit Trend",
            labels={
                "value": "Amount ($)",
                "Month": "Month",
                "variable": "Metric"
            }
        )

        fig1.update_layout(
            hovermode="x unified"
        )

        fig1.show()


        # ------------------------------------
        # 2. SALES BY CATEGORY
        # ------------------------------------

        category = (
            data
            .groupby("Category", as_index=False)
            .agg(
                Sales=("Sales", "sum")
            )
            .sort_values("Sales")
        )

        fig2 = px.bar(
            category,
            x="Sales",
            y="Category",
            orientation="h",
            title="Sales by Category",
            labels={
                "Sales": "Sales ($)",
                "Category": "Category"
            }
        )

        fig2.show()


        # ------------------------------------
        # 3. SALES BY PROVINCE
        # ------------------------------------

        province = (
            data
            .groupby("Province", as_index=False)
            .agg(
                Sales=("Sales", "sum")
            )
            .sort_values("Sales")
        )

        fig3 = px.bar(
            province,
            x="Sales",
            y="Province",
            orientation="h",
            title="Sales by Province",
            labels={
                "Sales": "Sales ($)",
                "Province": "Province"
            }
        )

        fig3.show()


        # ------------------------------------
        # 4. TOP 10 PRODUCTS
        # ------------------------------------

        products = (
            data
            .groupby("Product", as_index=False)
            .agg(
                Sales=("Sales", "sum")
            )
            .sort_values(
                "Sales",
                ascending=False
            )
            .head(10)
            .sort_values("Sales")
        )

        fig4 = px.bar(
            products,
            x="Sales",
            y="Product",
            orientation="h",
            title="Top 10 Products by Sales",
            labels={
                "Sales": "Sales ($)",
                "Product": "Product"
            }
        )

        fig4.show()


# --------------------------------------------
# CONNECT FILTERS
# --------------------------------------------

province_filter.observe(
    build_dashboard,
    names="value"
)

category_filter.observe(
    build_dashboard,
    names="value"
)

channel_filter.observe(
    build_dashboard,
    names="value"
)


# --------------------------------------------
# DISPLAY
# --------------------------------------------

display(
    widgets.HBox([
        province_filter,
        category_filter,
        channel_filter
    ])
)

display(dashboard)

build_dashboard()

HBox(children=(Dropdown(description='Province:', options=('All', 'Alberta', 'British Columbia', 'Manitoba', 'O…

Output()

I cleaned and validated the transaction data using Python, then built an interactive dashboard that allows management to filter sales performance by province, product category, and sales channel. The dashboard provides key KPIs and visual trends to help identify profitable products and business opportunities.

## Executive Performance Summary

The KPI section provides a quick overview of the selected business segment.

The metrics update automatically when the user changes the dashboard filters.

In [49]:
# ============================================
# STEP 22: PROFESSIONAL KPI CARDS
# ============================================

def create_kpi_card(title, value):

    return widgets.HTML(
        f"""
        <div style="
            border: 1px solid #dddddd;
            border-radius: 10px;
            padding: 15px;
            margin: 5px;
            min-width: 160px;
            text-align: center;
            background-color: #f8f9fa;
        ">
            <div style="
                font-size: 14px;
                font-weight: bold;
                color: #555555;
            ">
                {title}
            </div>

            <div style="
                font-size: 24px;
                font-weight: bold;
                margin-top: 8px;
            ">
                {value}
            </div>
        </div>
        """
    )


# Create KPI cards
kpi_cards = widgets.HBox([
    create_kpi_card("Total Sales", f"${kpi_sales.item():,.0f}"),
    create_kpi_card("Total Profit", f"${kpi_profit.item():,.0f}"),
    create_kpi_card("Orders", f"{kpi_orders:,}"),
    create_kpi_card("Average Order Value", f"${kpi_aov.item():,.0f}"),
    create_kpi_card("Profit Margin", f"{kpi_margin.item():.2%}")
])

display(kpi_cards)

HBox(children=(HTML(value='\n        <div style="\n            border: 1px solid #dddddd;\n            border-…

# Final Interactive Sales Dashboard

This dashboard combines the cleaned dataset, business KPIs, and interactive visualizations into one management view.

Users can filter the dashboard by:

- Province
- Category
- Sales Channel

The dashboard automatically updates the KPIs and charts based on the selected filters.

### Purpose

The dashboard helps management quickly identify sales trends, profitable areas, high-performing products, and opportunities for improvement.

In [50]:
# ============================================
# STEP 23: FINAL INTERACTIVE SALES DASHBOARD
# ============================================

import ipywidgets as widgets
from IPython.display import display, clear_output

# --------------------------------------------
# FILTERS
# --------------------------------------------

province_filter = widgets.Dropdown(
    options=["All"] + sorted(clean_sales["Province"].unique()),
    value="All",
    description="Province:"
)

category_filter = widgets.Dropdown(
    options=["All"] + sorted(clean_sales["Category"].unique()),
    value="All",
    description="Category:"
)

channel_filter = widgets.Dropdown(
    options=["All"] + sorted(clean_sales["Sales_Channel"].unique()),
    value="All",
    description="Channel:"
)

dashboard_output = widgets.Output()


# --------------------------------------------
# DASHBOARD FUNCTION
# --------------------------------------------

def update_final_dashboard(change=None):

    data = clean_sales.copy()

    # Apply filters
    if province_filter.value != "All":
        data = data[
            data["Province"] == province_filter.value
        ]

    if category_filter.value != "All":
        data = data[
            data["Category"] == category_filter.value
        ]

    if channel_filter.value != "All":
        data = data[
            data["Sales_Channel"] == channel_filter.value
        ]

    with dashboard_output:

        clear_output(wait=True)

        if data.empty:
            print("No data matches the selected filters.")
            return

        # ------------------------------------
        # KPI CALCULATIONS
        # ------------------------------------

        sales = data["Sales"].sum()
        profit = data["Profit"].sum()
        orders = data["Order_ID"].nunique()

        aov = sales / orders
        margin = profit / sales

        # ------------------------------------
        # KPI CARDS
        # ------------------------------------

        kpi_cards = widgets.HBox([
            create_kpi_card(
                "Total Sales",
                f"${sales:,.0f}"
            ),

            create_kpi_card(
                "Total Profit",
                f"${profit:,.0f}"
            ),

            create_kpi_card(
                "Orders",
                f"{orders:,}"
            ),

            create_kpi_card(
                "Average Order Value",
                f"${aov:,.0f}"
            ),

            create_kpi_card(
                "Profit Margin",
                f"{margin:.2%}"
            )
        ])

        display(kpi_cards)

        print("\n")


        # ------------------------------------
        # 1. SALES & PROFIT TREND
        # ------------------------------------

        monthly = (
            data
            .groupby("Month", as_index=False)
            .agg(
                Sales=("Sales", "sum"),
                Profit=("Profit", "sum")
            )
        )

        fig1 = px.line(
            monthly,
            x="Month",
            y=["Sales", "Profit"],
            markers=True,
            title="Sales and Profit Trend",
            labels={
                "value": "Amount ($)",
                "Month": "Month",
                "variable": "Metric"
            }
        )

        fig1.update_layout(
            hovermode="x unified"
        )

        fig1.show()


        # ------------------------------------
        # 2. SALES BY CATEGORY
        # ------------------------------------

        category = (
            data
            .groupby("Category", as_index=False)
            .agg(
                Sales=("Sales", "sum")
            )
            .sort_values("Sales")
        )

        fig2 = px.bar(
            category,
            x="Sales",
            y="Category",
            orientation="h",
            title="Sales by Category",
            labels={
                "Sales": "Sales ($)",
                "Category": "Category"
            }
        )

        fig2.show()


        # ------------------------------------
        # 3. SALES BY PROVINCE
        # ------------------------------------

        province = (
            data
            .groupby("Province", as_index=False)
            .agg(
                Sales=("Sales", "sum")
            )
            .sort_values("Sales")
        )

        fig3 = px.bar(
            province,
            x="Sales",
            y="Province",
            orientation="h",
            title="Sales by Province",
            labels={
                "Sales": "Sales ($)",
                "Province": "Province"
            }
        )

        fig3.show()


        # ------------------------------------
        # 4. TOP 10 PRODUCTS
        # ------------------------------------

        products = (
            data
            .groupby("Product", as_index=False)
            .agg(
                Sales=("Sales", "sum"),
                Profit=("Profit", "sum")
            )
            .sort_values(
                "Sales",
                ascending=False
            )
            .head(10)
            .sort_values("Sales")
        )

        fig4 = px.bar(
            products,
            x="Sales",
            y="Product",
            orientation="h",
            title="Top 10 Products by Sales",
            labels={
                "Sales": "Sales ($)",
                "Product": "Product"
            },
            hover_data=["Profit"]
        )

        fig4.show()


# --------------------------------------------
# CONNECT FILTERS
# --------------------------------------------

province_filter.observe(
    update_final_dashboard,
    names="value"
)

category_filter.observe(
    update_final_dashboard,
    names="value"
)

channel_filter.observe(
    update_final_dashboard,
    names="value"
)


# --------------------------------------------
# DISPLAY DASHBOARD
# --------------------------------------------

display(
    widgets.HBox([
        province_filter,
        category_filter,
        channel_filter
    ])
)

display(dashboard_output)

update_final_dashboard()

HBox(children=(Dropdown(description='Province:', options=('All', 'Alberta', 'British Columbia', 'Manitoba', 'O…

Output()

## Final Project Summary

This project demonstrates an end-to-end data analytics workflow for a fictional Canadian small-business retailer.

The raw sales data was profiled, cleaned, validated, analyzed, and transformed into an interactive management dashboard using Python.

### Key Results

* **Total Sales:** $6.52M
* **Total Profit:** $2.05M
* **Total Orders:** 9,978
* **Average Order Value:** $653.62
* **Overall Profit Margin:** 31.37%
* **Repeat Customer Rate:** 85.71%

### Key Business Insights

* **Electronics** generated the highest sales and profit among the product categories.
* **Laptop Pro 14** was the strongest individual product by sales and profit.
* **Ontario** generated the highest total sales, followed closely by Alberta.
* **Online sales** were the largest contributor by sales and profit.
* The business showed a strong **repeat-customer rate of 85.71%**, indicating strong customer retention.
* Discount levels showed that profitability does not follow a simple linear relationship with discount percentage, so discount decisions should be evaluated based on sales volume, revenue, and margin together.

### Business Value

The interactive dashboard allows management to filter performance by **province, category, and sales channel** and quickly evaluate changes in sales, profit, orders, average order value, and profit margin.

This project demonstrates practical skills in:

* Data cleaning and preparation
* Data validation
* Exploratory data analysis
* KPI development
* Business intelligence
* Interactive dashboard development
* Translating data into actionable business insights

> **Portfolio Note:** This is a fictional portfolio project created to demonstrate practical data analytics and business intelligence skills. No real customer information is used.